Update fastled.rst
OttoWinter/esphomedocs pull request #1088
Opened 2021-04-05 23:45 UTC by andrewerrington

I'm sure I submitted this already. A added a note to say that using GPIO16 on the ESP8266 to drive the LED data line. I found this casually referenced in a couple of places online, but only after I had discovered the problem empirically.

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2021-05-09 22:10 UTC, frenck requested changes

2021-05-09 22:10 UTC, frenck commented on components/light/fastled.rst
> +    On ESP8266 you should avoid using GPIO16 (D0 on Wemos D1 Mini Pro) to drive the data line of the LED.
Hi there @andrewerrington!

Thanks for opening up a contribution, however, could you elaborate on why that is?

2021-05-09 22:20 UTC, andrewerrington commented
I discovered it empirically. But here's a discussion confirming that it
doesn't work as expected, together with modified code to make it work.

https://github.com/adafruit/Adafruit_NeoPixel/issues/221

On Mon, 10 May 2021, 10:11 Franck Nijhof, ***@***.***> wrote:

> Assigned #1088 <https://github.com/esphome/esphome-docs/pull/1088> to
> @andrewerrington <https://github.com/andrewerrington>.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome-docs/pull/1088#event-4712005828>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXJVTENLXHXVQHZ25HQVJLTM4B75ANCNFSM42NUVM6Q>
> .
>

2021-05-09 22:22 UTC, frenck commented
Sure, but my comment/hint was: The change in the documentation does not tell the reading why that is. So maybe extend this part to not only tell: "What not to do", but also: "Why one should not do it".

2021-05-09 22:36 UTC, andrewerrington commented
I spent several hours trying to figure out why it didn't work. I finally
discovered that it was known not to work because GPIO16 is electrically
different to the other I/Os. I decided to add a simple warning to the
documentation so that others would not waste their time. You are free to
ignore my pull request, or re-word the warning, or fix the code so that the
warning is redundant.

The solution I chose was to use a different GPIO.

On Mon, 10 May 2021, 10:22 Franck Nijhof, ***@***.***> wrote:

> Sure, but my comment/hint was: The change in the documentation does not
> tell the reading why that is. So maybe extend this part to not only tell:
> "What not to do", but also: "Why one should not do it".
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome-docs/pull/1088#issuecomment-835909283>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXJVTB33WBHZD4JVIQUDFLTM4DKJANCNFSM42NUVM6Q>
> .
>

2021-05-09 22:39 UTC, frenck commented
? I'm not understanding your response completely. I've simply added a review comment on a PR you are doing; that is might be nice to adjust the PR a little so others can understand why.

That sounds reasonable and isn't much to ask, right?

2021-05-09 23:22 UTC, andrewerrington commented
I don't really have anything more to add. There is a problem using GPIO16
with fastled to drive WS8212 LEDs. My pull request was intended to alert
people to that fact.


On Mon, 10 May 2021, 10:40 Franck Nijhof, ***@***.***> wrote:

> ? I'm not understanding your response completely. I've simply added a
> review comment on a PR you are doing; that is might be nice to adjust the
> PR a little so others can understand why.
>
> That sounds reasonable and isn't much to ask, right?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome-docs/pull/1088#issuecomment-835915197>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXJVTFKQ5INU6NA5HJK76TTM4FMVANCNFSM42NUVM6Q>
> .
>

2021-05-17 13:46 UTC, frenck commented
Closing this PR as there is no follow-up on the change request from the review.

2021-05-17 13:46 UTC, closed without merging

2021-05-17 22:21 UTC, andrewerrington commented
Have you fixed the problem? Can we now use GPIO16? Excellent!

On Tue, 18 May 2021, 01:47 Franck Nijhof, ***@***.***> wrote:

> Closing this PR as there is no follow-up on the change request from the
> review.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome-docs/pull/1088#issuecomment-842338339>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXJVTFALA5IQWKFLC6JZ63TOEM6BANCNFSM42NUVM6Q>
> .
>

2021-05-18 00:42 UTC, frenck commented
No, I asked to update the PR adding the reason to the line you've added. You didn't and seemed like not prepared to do so, hence I closed the PR.

2021-05-18 00:48 UTC, andrewerrington commented
Ok, so you haven't fixed the problem, you refuse to allow my warning about
the problem to be included in the documentation, and you refuse to alter
what I wrote to be more like what you want (and I am not really sure what
you want, so I can't do it myself).

Remind me again why it's so hard to get people to contribute to open source
projects.


On Tue, 18 May 2021, 12:42 Franck Nijhof, ***@***.***> wrote:

> No, I asked to update the PR adding the reason to the line you've added.
> You didn't and seemed like not prepared to do so, hence I closed the PR.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome-docs/pull/1088#issuecomment-842737258>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXJVTG5CXEPBTYD5O34TU3TOGZXZANCNFSM42NUVM6Q>
> .
>