Update dallas.rst
OttoWinter/esphomedocs pull request #1100
Opened 2021-04-13 06:19 UTC by frspp

Added: line 41 note from io

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2021-04-13 17:25 UTC, glmnet commented
Did you manage to setup this with an input only pin?

2021-04-13 18:32 UTC, frspp commented
> Did you manage to setup this with an input only pin?

No. It needs input and output.

2021-04-13 18:34 UTC, glmnet commented
Ahh, my poor English.

I mean if you tried to get this running with an input only pin and failed of course, in that case how you realized it wasn't possible. I did not check, but ESPHome should tell you in this case the configuration is invalid

2021-04-14 11:06 UTC, frspp commented
> Ahh, my poor English.
> 
> I mean if you tried to get this running with an input only pin and failed of course, in that case how you realized it wasn't possible. I did not check, but ESPHome should tell you in this case the configuration is invalid
Sensor did not work so I did some googling and read that it needs IO. Compile/logger did not give anything about the sensor. Changed to another pin and still the sensor is not working so there is something wrong with my setup still.

2021-04-14 12:32 UTC, glmnet commented
which pin you've tried initially?

2021-04-14 13:04 UTC, glmnet commented
I'm adding this check https://github.com/esphome/esphome/pull/1692 so this should be catch by validation.

2021-04-14 16:31 UTC, frspp commented
> which pin you've tried initially?

Board is NodeMCU ESP32 38pin. First I tried pin GPIO39 ('SN'). 

Now it is on GPIO32, which is closest IO pin to 3v3.

2021-05-09 22:18 UTC, frenck requested changes
Thanks, @frspp!

Left some small rewording suggestions. Could you take a look?

Thanks! 👍 

../Frenck 🚂

2021-05-09 22:18 UTC, frenck commented on components/sensor/dallas.rst
> +massively long wires, in most cases) between ``3.3V`` and the data pin.
```suggestion
about 4.7KΩ. For this, connect a resistor of *about* 4.7KΩ between ``3.3V``
and the data pin. Values +/- 1KΩ will, in most cases, work fine as well,
if you don't have massively long wires.
```

2021-05-09 22:18 UTC, frenck commented on components/sensor/dallas.rst
> +- **pin** (**Required**, number): The pin the sensor bus is connected to. NOTE: 1-wire is a bi-directional bus so it requires both input and output from pin.
```suggestion
- **pin** (**Required**, number): The pin the sensor bus is connected to. Please note that 1-wire is a bi-directional bus so it requires both input and output from the pin.
```

2021-09-13 20:26 UTC, oxan requested changes

2021-09-13 20:26 UTC, oxan commented on components/sensor/dallas.rst
> +and the data pin. Values +/- 1KΩ will, in most cases, work fine as well,
```suggestion
and the data pin. Values ± 1KΩ will, in most cases, work fine as well,
```

2021-11-13 14:49 UTC, merged