Contribution page: Converting from "I" to "we" wording
OttoWinter/esphomedocs pull request #1104
Opened 2021-04-15 17:29 UTC by spacegaier

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [X] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2021-04-15 23:06 UTC, glmnet commented
Actually this opinion can be removed from docs. It really is not adding technical documentation. 

Besides Otto changed his mind and there are some code automation tools which relies on rst so changing to markdown wouldn't be suggested. 

See also https://github.com/esphome/feature-requests/issues/803

2021-05-10 10:54 UTC, frenck requested changes
@spacegaier How about just this :)

2021-05-10 10:54 UTC, frenck commented on guides/contributing.rst
>  RST primer:
```suggestion
Here's a quick RST primer:
```

2021-05-10 11:05 UTC, spacegaier commented
Looks like someone else already changed that (https://github.com/esphome/esphome-docs/pull/1052) => my PR is now obsolete.

2021-05-10 11:05 UTC, closed without merging