rf_bridge: add new actions
OttoWinter/esphomedocs pull request #1193
Opened 2021-05-23 15:33 UTC by ianchi

## Description:

Adds documentation for proposed new functionalities in `rf_bridge`

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#1819

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2021-05-23 20:29 UTC, frenck requested changes

2021-05-23 20:29 UTC, frenck commented on components/rf_bridge.rst
> +If you have *Portisch* firmware installed, this raw codes can be obtained with the help of :ref:`rf_bridge-start_bucket_sniffing_action`
```suggestion
If you have *Portisch* firmware installed, these raw codes can be obtained with the help of :ref:`rf_bridge-start_bucket_sniffing_action`
```

2021-05-23 20:29 UTC, frenck commented on components/rf_bridge.rst
> +-------------------------------------------
```suggestion
``rf_bridge.start_bucket_sniffing`` Action
------------------------------------------
```

2021-05-23 20:29 UTC, frenck commented on components/rf_bridge.rst
> +    For this you can use the tool `BitBucket Converter <https://bbconv.hrbl.pl/>`__
```suggestion
    For this, you can use the tool `BitBucket Converter <https://bbconv.hrbl.pl/>`__
```

2021-05-23 20:29 UTC, frenck commented on components/rf_bridge.rst
> +    There seems to be an overflow problem in Portisch firmware and after a short while the bucket sniffing stops.
```suggestion
    There seems to be an overflow problem in Portisch firmware and after a short while, the bucket sniffing stops.
```

2021-05-23 20:29 UTC, frenck commented on components/rf_bridge.rst
> +    You should re-call the action to reset and start sniffing again
```suggestion
    You should re-call the action to reset and start sniffing again.
```

2021-05-23 20:29 UTC, frenck commented on components/rf_bridge.rst
> +- **duration** (**Required**, string, :ref:`templatable <config-templatable>`): beep duration in milliseconds
```suggestion
- **duration** (**Required**, string, :ref:`templatable <config-templatable>`): beep duration in milliseconds.
```

2021-05-24 01:30 UTC, ianchi commented on components/rf_bridge.rst
> +-------------------------------------------
updated

2021-05-24 01:31 UTC, ianchi commented on components/rf_bridge.rst
> +If you have *Portisch* firmware installed, this raw codes can be obtained with the help of :ref:`rf_bridge-start_bucket_sniffing_action`
updated

2021-05-24 01:32 UTC, ianchi commented on components/rf_bridge.rst
> +    There seems to be an overflow problem in Portisch firmware and after a short while the bucket sniffing stops.
updated

2021-05-24 01:32 UTC, ianchi commented on components/rf_bridge.rst
> +    For this you can use the tool `BitBucket Converter <https://bbconv.hrbl.pl/>`__
updated

2021-05-24 01:34 UTC, ianchi commented on components/rf_bridge.rst
> +    You should re-call the action to reset and start sniffing again
updated

2021-05-24 01:34 UTC, ianchi commented on components/rf_bridge.rst
> +- **duration** (**Required**, string, :ref:`templatable <config-templatable>`): beep duration in milliseconds
updated

2021-05-31 19:19 UTC, jesserockz approved these changes

2021-05-31 19:24 UTC, merged