Update diy.rst
OttoWinter/esphomedocs pull request #1261
Opened 2021-06-18 06:22 UTC by haade-administrator

add lines with config github

2021-06-19 15:34 UTC, frenck requested changes
This breaks the layout at this point

![image](https://user-images.githubusercontent.com/195327/122647448-8e381500-d124-11eb-8c86-325adb2e7dde.png)

Additionally, you seem to add an GitHub edit link?

2021-06-20 20:27 UTC, jesserockz commented on guides/diy.rst
> +:ghedit:`ESP8266 lysignal Yunshan 7v-30v <https://gist.github.com/haade-administrator/ba9b6667ece8269cd37f64e34e908977/>`___ by :ghuser:`haade` <https://www.haade.fr>`___
```suggestion
`ESP8266 lysignal Yunshan 7v-30v <https://gist.github.com/haade-administrator/ba9b6667ece8269cd37f64e34e908977/>`___ by :ghuser:`haade` <https://www.haade.fr>`___
```

2021-06-20 20:30 UTC, jesserockz commented on guides/diy.rst
> +- `ESP8266 lysignal Yunshan 7v-30v <https://gist.github.com/haade-administrator/ba9b6667ece8269cd37f64e34e908977/>`___ by :ghuser:`haade` <https://www.haade.fr>`___
```suggestion
- `ESP8266 lysignal Yunshan 7v-30v <https://gist.github.com/haade-administrator/ba9b6667ece8269cd37f64e34e908977/>`__ by :ghuser:`haade-administrator`
```

2021-06-23 14:23 UTC, frenck approved these changes

2021-06-23 14:23 UTC, merged