Add documentation for Daly BMS Component
OttoWinter/esphomedocs pull request #1390
Opened 2021-08-14 20:51 UTC by s1lvi0

## Description:

Added support for Daly Smart BMS

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2021-08-18 08:07 UTC, jesserockz requested changes
A few simple things to fix.
hint: You can apply them all in one commit in the [files](https://github.com/esphome/esphome-docs/pull/1390/files) tab of the PR

2021-08-18 08:07 UTC, jesserockz commented on components/sensor/daly_bms.rst
> +=======================================
```suggestion
Daly BMS
========
```

2021-08-18 08:07 UTC, jesserockz commented on components/sensor/daly_bms.rst
> +    :description: Instructions for setting up a Daly Smart MBS
```suggestion
    :description: Instructions for setting up a Daly Smart BMS
```

2021-08-18 08:07 UTC, jesserockz commented on components/sensor/daly_bms.rst
> +The ``Daly BMS`` sensor platform allows you to use a Daly smart BMS
```suggestion
The ``daly_bms`` sensor platform allows you to use a Daly smart BMS
```

2021-08-18 08:07 UTC, jesserockz commented on components/sensor/daly_bms.rst
> +The BMS communicate with board by :ref:`UART <uart>` protocol.
```suggestion
The BMS communicates via :ref:`UART <uart>`.
```

2021-08-18 08:07 UTC, jesserockz commented on components/sensor/daly_bms.rst
> +------------------------
```suggestion

Component/Hub
-------------

Configuration variables:
************************
```

2021-08-18 08:07 UTC, jesserockz commented on components/sensor/daly_bms.rst
> +Configuration variables:
```suggestion
Sensor:
-------
A sensor platform to read BMS data

Configuration variables:
************************
```

2021-08-18 08:07 UTC, jesserockz commented on components/sensor/daly_bms.rst
> +Configuration variables:
```suggestion
Text Sensor:
------------
Text sensor that indicates the status of BMS.

Configuration variables:
************************
```

2021-08-18 08:07 UTC, jesserockz commented on components/sensor/daly_bms.rst
> +Configuration variables:
```suggestion
Binary Sensor:
--------------
Binary sensor that indicates the status of MOS.

Configuration variables:
************************
```

2021-08-18 08:07 UTC, jesserockz commented on components/sensor/daly_bms.rst
> +------------------------
```suggestion
UART Connection:
----------------
```

2021-08-18 08:07 UTC, jesserockz commented on components/sensor/daly_bms.rst
> +  - All other options from :ref:`Sensor <config-sensor>`.
```suggestion
  - All other options from :ref:`Binary Sensor <config-binary_sensor>`.
```

2021-08-18 08:07 UTC, jesserockz commented on components/sensor/daly_bms.rst
> +  - All other options from :ref:`Sensor <config-sensor>`.
```suggestion
  - All other options from :ref:`Binary Sensor <config-binary_sensor>`.
```

2021-08-18 08:07 UTC, jesserockz commented on components/sensor/daly_bms.rst
> +  - All other options from :ref:`Sensor <config-sensor>`.
```suggestion
  - All other options from :ref:`Text Sensor <config-text_sensor>`.
```

2021-09-14 19:13 UTC, oxan requested changes
Looks good, just a few minor textual changes.

2021-09-14 19:13 UTC, oxan commented on components/sensor/daly_bms.rst
> +The ``daly_bms`` sensor platform allows you to use a Daly smart BMS
```suggestion
The ``daly_bms`` sensor platform allows you to use a Daly Smart BMS
```

2021-09-14 19:13 UTC, oxan commented on components/sensor/daly_bms.rst
> +************************
There should either be something in this section, or it should be removed :)

2021-09-14 19:13 UTC, oxan commented on components/sensor/daly_bms.rst
> +- **status** (*Optional*): The BMS Status (Charging, Disgharging, Stationary).
```suggestion
- **status** (*Optional*): The BMS Status (Charging, Discharging, Stationary).
```

2021-09-14 19:13 UTC, oxan commented on components/sensor/daly_bms.rst
> +- **charging_mos_enabled** (*Optional*): The BMS charging mos status to enable the reacharge of the battery.
```suggestion
- **charging_mos_enabled** (*Optional*): The BMS charging MOS status to enable the recharge of the battery.
```

2021-09-14 19:13 UTC, oxan commented on components/sensor/daly_bms.rst
> +- **discharging_mos_enabled** (*Optional*): The BMS Discharging mos status to enable the load.
```suggestion
- **discharging_mos_enabled** (*Optional*): The BMS discharging MOS status to enable the load.
```

2021-09-14 19:13 UTC, oxan commented on components/sensor/daly_bms.rst
> +- All other options from :ref:`Binary Sensor <config-binary_sensor>`.
```suggestion
  - All other options from :ref:`Binary Sensor <config-binary_sensor>`.
```

2021-09-14 19:13 UTC, oxan commented on components/sensor/daly_bms.rst
> +- All other options from :ref:`Binary Sensor <config-binary_sensor>`.
```suggestion
  - All other options from :ref:`Binary Sensor <config-binary_sensor>`.
```

2021-09-22 10:03 UTC, merged