Note to set ``optimistic`` when using HA to set
OttoWinter/esphomedocs pull request #1437
Opened 2021-08-31 19:58 UTC by mnaz

For a while I was trying to use the Number Template and I couldn't figure why changes I made from the HA UI did not apply in my ESP device.
I think adding a note here will help or revising the text that already exists.
It also might be nice to add a note to have ``restore_count`` set also.

This is what I used.

    number:
      - platform: template
        name: Trigger Count
        id: trigger_count
        icon: "mdi:sync"
        restore_value: true
        optimistic: true
        initial_value: 8
        max_value: 10
        min_value: 1
        step: 1

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2021-09-02 19:59 UTC, oxan requested changes

2021-09-02 19:59 UTC, oxan commented on components/number/template.rst
> +  This must be set to ``true`` inorder for changes from Home Assistant to be applied.
This is not true, you can also have a `set_action` that does something based on the changed value from HA and a `lambda` that reports back what the current value is.

2021-09-11 13:30 UTC, oxan commented
I think #1441 adequately took care of this problem (with the related PR it's no longer even possible to create numbers with `optimistic: false` without setting a `set_action`). Feel free to reopen if you disagree.

2021-09-11 13:30 UTC, closed without merging

2021-09-13 15:08 UTC, mnaz commented
perfect, I just wanted to help avoid others the confusion.