Add DS3231 Component
OttoWinter/esphomedocs pull request #1531
Opened 2021-10-15 14:19 UTC by nuttytree

## Description:
Adds a DS3231 Real Time Clock Component that includes:

Core component that handles communication with the device
Options on the core component to setup alarms
Options on the core component to set the mode and frequency of the square wave output
Action automations to set the alarms
Trigger automations for when the alarms are triggered
Action automations to reset the alarms after they have been triggered
Action automations to set the mode and frequency of the square wave output
Time component
Action automations to read/write the time from/to the RTC
Temperature sensor

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#2501

## Checklist:

  - [X] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [X] Link added in `/index.rst` when creating new documents for new components or cookbook.

2021-10-15 18:45 UTC, oxan requested changes

2021-10-15 18:45 UTC, oxan commented on components/ds3231.rst
> +1024hz, 4096hz, or 8192hz, a 32.768kHz output, and a temperature sensor. It uses :ref:`I²C Bus <i2c>` for communication.
```suggestion
that includes 2 alarms, an output that can be triggered by either alarm or output a continuous square wave at 1 Hz,
1024 Hz, 4096 Hz, or 8192 Hz, a 32.768 kHz output, and a temperature sensor. It uses :ref:`I²C Bus <i2c>` for communication.
```

2021-10-15 18:45 UTC, oxan commented on components/ds3231.rst
> +- **square_wave_frequncy** (*Optional*, enum): The frequency of the square wave output. Defaults to ``8192HZ``.
```suggestion
- **square_wave_frequency** (*Optional*, enum): The frequency of the square wave output. Defaults to ``8192HZ``.
```

2021-10-15 18:45 UTC, oxan commented on components/ds3231.rst
> +    - ``MATCH_SECOND`` - Alarm is triggered everytime the second matches the provided value.
"everytime" should be "every time" throughout this file.

2021-10-15 18:45 UTC, oxan commented on components/ds3231.rst
> +        - fan.ds3231.set_alarm_1:
`fan.`? (also below).

2021-10-18 13:33 UTC, nuttytree commented on components/ds3231.rst
> +1024hz, 4096hz, or 8192hz, a 32.768kHz output, and a temperature sensor. It uses :ref:`I²C Bus <i2c>` for communication.
Updated

2021-10-18 13:34 UTC, nuttytree commented on components/ds3231.rst
> +- **square_wave_frequncy** (*Optional*, enum): The frequency of the square wave output. Defaults to ``8192HZ``.
Fixed

2021-10-18 13:34 UTC, nuttytree commented on components/ds3231.rst
> +        - fan.ds3231.set_alarm_1:
Fixed

2021-10-18 13:34 UTC, nuttytree commented on components/ds3231.rst
> +    - ``MATCH_SECOND`` - Alarm is triggered everytime the second matches the provided value.
Fixed

2021-10-21 21:14 UTC, oxan approved these changes
Ready to be merged when parent PR is.

2021-12-21 02:31 UTC, nuttytree commented
Sorry for the delay on getting this tested, I was out with Covid for 3 weeks.  Trying to get caught back up so I can get this tested.

2022-02-27 01:46 UTC, closed without merging