Add mopeka pro check integration docs
OttoWinter/esphomedocs pull request #1564
Opened 2021-10-23 17:44 UTC by spbrogan

## Description:

**Related issue (if applicable):** fixes <https://github.com/esphome/feature-requests/issues/1445>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#2618

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2021-12-24 01:43 UTC, spbrogan commented
I don't understand the development process.  How do i get the code PR merged.  It has been ready for a couple of months.   I did update the code pr today since i was using the code on a new node and wanted it rebased on current dev.

2021-12-29 07:50 UTC, jesserockz commented
Hi @spbrogan The development process is like this: myself or one of only a handful of others will review the code when they have time.
Don't worry too much about this PR going stale as when someone reviews the code PR they can reopen this one again for review and merging.

2022-02-21 00:52 UTC, jesserockz requested changes

2022-02-21 00:52 UTC, jesserockz commented on components/sensor/mopeka_ble.rst
> +  - All other options from :ref:`Sensor <config-sensor>`.
The sensor base config has these already, no need to repeat here.
```suggestion
- **level** (*Optional*): The percentage of full for the tank sensor

  - All options from :ref:`Sensor <config-sensor>`.

- **distance** (*Optional*): The raw distance/depth of the liquid for the sensor in mm.

  - All options from :ref:`Sensor <config-sensor>`.

- **temperature** (*Optional*): The information for the temperature sensor.
  This temperature is on the sensor and is not calibrated to ambient temperature.

  - All options from :ref:`Sensor <config-sensor>`.

- **battery_level** (*Optional*): The information for the battery percentage
  sensor.  Sensor uses a standard CR2032 battery.

  - All options from :ref:`Sensor <config-sensor>`.
```

2022-02-27 08:57 UTC, jesserockz approved these changes

2022-02-28 04:10 UTC, jesserockz commented on components/sensor/mopeka_ble.rst
> +  measuring.
```suggestion
- **tank_type** (**Required**): The tank type the sensor is measuring. See below.
```

2022-02-28 22:30 UTC, merged