Gree i feel
OttoWinter/esphomedocs pull request #1607
Opened 2021-11-11 01:02 UTC by cmroche

## Description:

Adding notes about sending temperature with IR Climate to **greeyac** compatible devices.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#2694

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2021-11-12 22:33 UTC, cmroche commented
This is parented to the wrong branch, I'll need to force push again soon to fix it.

2021-11-14 15:04 UTC, oxan requested changes
The docs LGTM, but there's another unrelated commit in this branch. Could you rebase and remove that one, please?

2021-11-14 15:10 UTC, oxan approved these changes
Thanks!

2021-11-14 15:11 UTC, cmroche commented
@oxan Fixed.

2021-11-14 15:13 UTC, merged