Added note about nec protocol fix
OttoWinter/esphomedocs pull request #1618
Opened 2021-11-14 13:02 UTC by dudanov

## Description:

Added note about nec protocol fix.

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#2534

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2021-11-14 13:29 UTC, davet2001 requested changes
Minor rewording suggested

2021-11-14 13:29 UTC, davet2001 commented on components/remote_transmitter.rst
> +    Therefore, in earlier versions of the configuration, it is necessary to reverse the order of the address and command bits.
Suggested wording:
Therefore, if the the configuration file has come from an earlier version of ESPhome, it is necessary to reverse the order of the address and command bits when moving to 2021.11 or above.

2021-11-14 14:45 UTC, dudanov commented
> Minor rewording suggested

Done.

2021-11-14 14:48 UTC, davet2001 approved these changes
Looks good! Thanks! 👍

2021-11-14 21:07 UTC, jesserockz requested changes
This breaking change will not be merged for the .11 release. Will make sure to put it for next though.

2021-11-14 21:07 UTC, jesserockz commented on components/remote_transmitter.rst
> +    In version 2021.11, the order of transferring bits was corrected from MSB to LSB in accordance with the NEC standard.
```suggestion
    In version 2021.12, the order of transferring bits was corrected from MSB to LSB in accordance with the NEC standard.
```

2021-11-14 21:07 UTC, jesserockz commented on components/remote_transmitter.rst
> +    Therefore, if the the configuration file has come from an earlier version of ESPhome, it is necessary to reverse the order of the address and command bits when moving to 2021.11 or above.
```suggestion
    Therefore, if the the configuration file has come from an earlier version of ESPhome, it is necessary to reverse the order of the address and command bits when moving to 2021.12 or above.
```

2021-11-20 05:13 UTC, kbx81 commented
Should this note be added to to the remote receiver doc, too? I just discovered this change tonight when my NEC receiver stopped working. 🙃

2021-11-20 06:54 UTC, dudanov commented
> Should this note be added to to the remote receiver doc, too? I just discovered this change tonight when my NEC receiver stopped working. upside_down_face

Thank you for reminding about receiver.

2021-11-20 07:59 UTC, davet2001 commented
> Should this note be added to to the remote receiver doc, too? I just discovered this change tonight when my NEC receiver stopped working. 🙃

Yes! +1 from me.

2021-11-20 19:32 UTC, jesserockz approved these changes

2021-11-20 19:33 UTC, merged