Quantile filter
OttoWinter/esphomedocs pull request #1715
Opened 2021-12-09 21:47 UTC by konikvranik

## Description:

Documents quantile filter

**Related issue (if applicable):** fixes esphome/feature-requests#1543

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#2900

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2021-12-12 21:53 UTC, jesserockz approved these changes

2021-12-13 17:34 UTC, oxan requested changes

2021-12-13 17:34 UTC, oxan commented on components/sensor/index.rst
> +A `simple moving quantile <https://www.wikiwand.com/en/Quantile>`__
Please link to just the regular Wikipedia site, instead of a third-party copy.

2021-12-13 17:34 UTC, oxan commented on components/sensor/index.rst
> +- **window_size** (*Optional*, int): The number of values over which to calculate the median
Copy/paste error, median -> quantile.

2021-12-13 17:34 UTC, oxan commented on components/sensor/index.rst
> +  be odd if you want an actual received value pushed out.
Copy/paste error, this doesn't apply to your filter.

2021-12-13 17:34 UTC, oxan commented on components/sensor/index.rst
> +  example, in above configuration the median is calculated after every 4th
Copy/paste error, median -> quantile.

2021-12-14 09:37 UTC, oxan commented on components/sensor/index.rst
> +- **quantile** (**Optional**, float): value from 0 to 1 to determine which quantile to pick.
```suggestion
- **quantile** (*Optional*, float): value from 0 to 1 to determine which quantile to pick.
```

2021-12-14 09:37 UTC, oxan approved these changes

2021-12-14 18:43 UTC, merged