Add AirGradient DIY Air Quality to cookbook
OttoWinter/esphomedocs pull request #1727
Opened 2021-12-16 09:10 UTC by ajfriesen

## Description:

I just added some documentation for the AirGradient DIY Air Quality sensor to the cookbook

I used the current branch because a new release is not needed.

**Related issue (if applicable):** not applicable

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** not applicable

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2021-12-19 19:25 UTC, jesserockz requested changes

2021-12-19 19:25 UTC, jesserockz commented on cookbook/air_gradient_diy_air_quality_sensor.rst
> +- You can download a 3D printeable case inkluding a wall mount bracket
```suggestion
- You can download a 3D printable case including a wall mount bracket
```

2021-12-19 19:25 UTC, jesserockz commented on cookbook/air_gradient_diy_air_quality_sensor.rst
> +    <iframe width="560" height="315" src="https://www.youtube.com/embed/Cmr5VNALRAg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" a
```suggestion
    <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/Cmr5VNALRAg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

2022-01-07 18:19 UTC, ajfriesen reviewed
Thanks for catching the errors!

I am not sure how to go from this point.
I can not approve that change.

2022-01-08 08:32 UTC, jesserockz approved these changes

2022-01-08 08:32 UTC, merged