Add documentation for Shelly Dimmer 2
OttoWinter/esphomedocs pull request #1753
Opened 2021-12-27 22:53 UTC by rnauber

## Description:

This is the documentation for using the [Shelly Dimmer 2](https://shelly.cloud/knowledge-base/devices/shelly-dimmer-2/) with esphome.

**Related issue:** fixes  https://github.com/esphome/feature-requests/issues/949

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes:** esphome/esphome#2954
## Checklist:

  - [X] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. 
   - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2022-01-28 10:06 UTC, playya commented
@rnauber I have a example config for shelly dimmer 1 in my branch: https://github.com/playya/esphome-docs/blob/shelly_dimmers/devices/shelly_dimmer1.yaml

2022-04-11 22:59 UTC, jesserockz requested changes
Just one comment about the firmware option, otherwise I think good to go

2022-04-11 22:59 UTC, jesserockz commented on components/light/shelly_dimmer.rst
> +- **firmware**  (**Optional**, string) Version string of the `firmware <https://github.com/jamesturton/shelly-dimmer-stm32>`_ that will be flashed on the microcontroller. The default is "51.5".
Can we update this with the new structure?

2022-04-12 19:41 UTC, jesserockz approved these changes

2022-04-14 01:14 UTC, merged