Patch 1
OttoWinter/esphomedocs pull request #1839
Opened 2022-01-23 17:13 UTC by guillempages

Update documentation according to PR https://github.com/esphome/esphome/pull/3100

## Description:
Add force_redirect and redirect_limit options

**Related issue (if applicable):**

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#3100

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2022-01-24 20:00 UTC, oxan requested changes
Can you rebase this upon the `next` branch? Right now your PR contains all changes from the `current` branch as well, which makes it hard to review.

2022-01-25 08:13 UTC, guillempages commented
Oops. Sorry :-(
I did that from the UI, and saw that I was pushing to the wrong branch, so I changed that, but I missed the fact that I had already branched off the wrong branch.
Fixed now.

2022-01-25 08:17 UTC, guillempages commented on components/http_request.rst
> +- **redirect_limit** (*Optional*, integer): Maximum amount of redirects to follow when enabled.
```suggestion
- **redirect_limit** (*Optional*, integer): Maximum amount of redirects to follow when enabled. Defaults to ``3``.
```

2022-01-25 08:20 UTC, oxan requested changes
No worries!

2022-01-25 08:20 UTC, oxan commented on components/http_request.rst
> +- **force_redirects** (*Optional*, boolean): Enable HTTP forced redirection. Defaults to ``true``.
Force -> follow:
```suggestion
- **follow_redirects** (*Optional*, boolean): Enable following HTTP redirects. Defaults to ``true``.
```

2022-01-25 08:40 UTC, guillempages commented on components/http_request.rst
> +- **force_redirects** (*Optional*, boolean): Enable HTTP forced redirection. Defaults to ``true``.
(facepalm)

2022-01-25 08:53 UTC, oxan approved these changes

2022-01-25 08:53 UTC, merged