Support for MS8607 PHT (Pressure Humidity Temperature) sensor
OttoWinter/esphomedocs pull request #1974
Opened 2022-03-18 02:26 UTC by e28eta

## Description:

Documentation for new component MS8607

**Related issue (if applicable):** fixes esphome/feature-requests#932

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#3307

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

I ran the image compression suggestion from https://esphome.io/guides/contributing.html and the file sizes I see are:

- `images/ms8607.jpg` 19k, with pixel dimensions 300x216 
- `components/sensor/images/ms8607-full.jpg` 150k, with pixel dimensions 774x556

2022-05-17 03:15 UTC, e28eta commented
I’m still hopeful the functional PR and docs PRs land

2022-07-17 04:49 UTC, e28eta commented
I’m still hopeful the functional PR and docs PR land

2023-01-02 05:14 UTC, e28eta commented
The force push 5 minutes ago was a no-conflict rebase onto the head of next, e189d6d85c5096a4ca890a9f88aef056bc16f9b2

2024-03-04 20:20 UTC, jesserockz requested changes

2024-03-04 20:20 UTC, jesserockz commented on components/sensor/ms8607.rst
> +  - All other options from :ref:`Sensor <config-sensor>`.
```suggestion
- **temperature** (**Required**): The information for the temperature sensor.
  All options from :ref:`Sensor <config-sensor>`.

- **pressure** (**Required**): The information for the pressure sensor.
  All options from :ref:`Sensor <config-sensor>`.

- **humidity** (**Required**): The information for the humidity sensor.
  - **address** (*Optional*, int): Manually specify the I²C address of
    the humidity sensor. Defaults to ``0x40``.
  - **i2c_id** (*Optional*, :ref:`config-id`): Manually specify the ID of the :ref:`I²C Component <i2c>` if your
    configuration uses multiple I²C buses. This should match the ``i2c_id`` documented below.
  - All other options from :ref:`Sensor <config-sensor>`.
```

2024-03-04 20:20 UTC, jesserockz approved these changes, later dismissed

2024-03-04 21:50 UTC, jesserockz approved these changes

2024-03-04 21:50 UTC, merged