Fixing subnet mask
OttoWinter/esphomedocs pull request #2005
Opened 2022-04-09 09:08 UTC by wilcomir

The subnet mask provided in the example is not compatible with the IPs provided.

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2022-04-09 09:22 UTC, wilcomir commented
To clarify, the documentation was - at least for me - confusing. I use the whole 10.x.x.x/8 at home, and I glanced over the mask since I saw the 10.x address.
Perhaps my edit was a bit too quick - maybe I could add a couple of sections, one for the more traditional 192.168.x.x address, and one for the full 10.x.x.x subnet.
This is based on the assumption that most people who use 10.x.x.x addresses use a /8 mask, which is at least debatable of course :)

I did have to pull my sonoff out of the wall to fix this so I think that while the edit can be improved, we should change something.

2022-04-14 04:05 UTC, jesserockz requested changes
This is not really correct to change as it is up to the user what their actual subnet is. I personally use 4 vlans
`10.1.1.0/24` `10.2.2.0/24` `10.5.5.0/24` and `10.6.6.0/24`

As mentioned in your comment, maybe better to change the entire example to use `192.168.1.0/24`

2022-04-14 05:41 UTC, wilcomir commented
Hey @jesserockz , I modified as you suggested. Cheers!

2022-04-14 06:35 UTC, jesserockz approved these changes
Thanks

2022-04-14 06:35 UTC, merged