Update thermostat.rst
OttoWinter/esphomedocs pull request #2041
Opened 2022-04-25 06:46 UTC by gvdhoven

Explained "default_mode" in more detail.

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2022-04-29 05:56 UTC, kbx81 commented
The examples we provide at the top are usually intended to illustrate the minimum configuration to get the component working -- while I don't feel terribly strongly about this, I think we should keep them that way in the interest of streamlining the documentation. If we added a line there every time someone didn't understand one of the options, it would end up looking like what I have in my [config](https://github.com/kbx81/esphome-configs/blob/62ad8ff9d2ad4e69b03b16aabeda80ac4ae8baa2/shared/esp_thermostat_nextion_common_config.yaml#L223-L317); I think it best we avoid that. 🙂 Also, based on what I know about it, I think it's also a safe assumption that most folks will not want the default mode to be a mode where the system is active.

I think the call-out you added is good and adds some clarity; I've got a couple suggestions in terms of wording to make it more consistent with the language/terms we use in the community. I'll leave an in-line comment or two in a moment.

2022-04-29 06:10 UTC, kbx81 requested changes
Some suggestions, as promised. 😄

2022-04-29 06:10 UTC, kbx81 commented on components/climate/thermostat.rst
> +        default_mode: heat_cool
I think we should strike this and keep the examples as simple/minimal as possible.

2022-04-29 06:10 UTC, kbx81 commented on components/climate/thermostat.rst
> +        default_mode: heat
Same as above

2022-04-29 06:10 UTC, kbx81 commented on components/climate/thermostat.rst
> +        default_mode: cool
Same as above

2022-04-29 06:10 UTC, kbx81 commented on components/climate/thermostat.rst
> +  not configured, you have to change the mode (once) via e.g. the UI of Home Assistant.
Let's re-word this so it's more consistent with the terms/phrasing we use in the community. Here's a suggestion:

```suggestion
This value is used the first time your device starts after ESPHome is initially installed onto it. Add
this option into your configuration if you want your thermostat component to start in a climate mode other
than ``off``.  If this option is not configured, you'll need to manually change the climate mode later via
the front end (Home Assistant), an ESPHome action, automation, or from within a lambda elsewhere in your
device's configuration.
```

2022-04-30 13:36 UTC, gvdhoven commented
All comments are resolved.

2022-05-02 00:48 UTC, kbx81 approved these changes
LGTM -- thanks!

2022-05-11 00:36 UTC, merged