Add online_image documentation
OttoWinter/esphomedocs pull request #2076
Opened 2022-05-14 13:25 UTC by guillempages

Add the documentation for the new feature "online image"

## Description:

**Related issue (if applicable):** related to esphome/feature-requests#1463

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#3255

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2022-07-14 04:22 UTC, guillempages commented
This is not stale, it is waiting on the code or to be reviewed.

2024-07-13 15:09 UTC, clydebarrow commented
Can I suggest the ability to specify an optional compile time image that acts as a placeholder until the downloaded image is available? I would assume this will need to be copied in `setup()`.

2024-07-13 15:22 UTC, nagyrobi commented
What kind of image files are supported?

2024-07-13 19:33 UTC, guillempages commented
@nagyrobi yes, for the moment only PNGs are supported. The code is "prepared" to add other formats (as long as the corresponding library supports "streaming decoding"), but the focus is on getting the basic functionality (i.e. PNG) in, before adding additional formats.

I did not document the image format on purpose, since the option "format: " is already implemented (but useless, since it only accepts PNG as a parameter), but I do see your point, that it would be nice to make the supported formats explicit in the documentation, and update it once a new format is added.

2024-07-13 19:37 UTC, guillempages commented
> Can I suggest the ability to specify an optional compile time image that acts as a placeholder until the downloaded image is available? I would assume this will need to be copied in `setup()`.

As mentioned in the code-PR: in a follow-up PR; not in the initial one.

2024-07-13 19:48 UTC, nagyrobi commented
> I did not document the image format on purpose

If you want this to be merged, at least _a note_ would be needed in order to avoid user confusion. They will assume any kind of image format is supported, just like in the offline image component.

2024-07-13 20:29 UTC, guillempages commented
I've added a sentence in the overall description; I'll upgrade it to a note tomorrow.

2024-07-15 22:45 UTC, clydebarrow commented
Two suggestions: consider moving this to its own page, rather than burying it in the Display section (there is other stuff in Display that needs the same, but no need to perpetuate that.)

Secondly, there needs to be more information on how to use it - how to actually trigger the download. Without extra config nothing happens because the `online_image` is a polling component but `update_interval` defaults to `never`.

2024-07-15 22:46 UTC, clydebarrow commented on components/display/index.rst
> +          it.image(0, 0, id(my_online_image))
```suggestion
          it.image(0, 0, id(my_online_image));
```

2024-07-21 14:25 UTC, guillempages commented on components/display/index.rst
> +          it.image(0, 0, id(my_online_image))
Thanks for catching this

2024-07-21 14:34 UTC, guillempages commented
I also thought, that the display component is having too many things inside, and graph, "image", "animation",... should be split out of that file, but thought I'd keep the new component consistent there.
I've moved it to a separate file now, and might create a separate PR to split those other components as well.

2024-08-06 06:00 UTC, jesserockz commented on index.rst
> +    Font Renderer, components/display/fonts, format-font.svg, dark-invert
```suggestion
```

2024-08-06 06:00 UTC, jesserockz commented on index.rst
> +    Online Image, components/online_image, image-sync-outline.svg, dark-invert
```suggestion
    Online Image, components/online_image, image-sync-outline.svg, dark-invert
    Display Menu Core, components/display_menu/index, folder-open.svg, dark-invert
    Graphical Display Menu, components/display_menu/graphical_display_menu, graphical_display_menu.png
    LCD Menu, components/display_menu/lcd_menu, lcd_menu.png
```

2024-08-06 07:46 UTC, jesserockz requested changes

2024-08-06 07:46 UTC, jesserockz commented on components/online_image.rst
> +
It's on the user to visit the above link to see how to configure the `http_request` component
```suggestion
```

2024-08-06 07:46 UTC, jesserockz commented on components/online_image.rst
> +        - component.update: my_online_image
Minimal config example only first please. A full example is allowed to go below the `Actions` section

2024-08-06 07:46 UTC, jesserockz commented on components/online_image.rst
> +- **use_transparency** (*Optional*, boolean): If set the alpha channel of the input image will be taken into account, and pixels with alpha < 127 will not be drawn. For image types without explicit a
```suggestion
- **use_transparency** (*Optional*, boolean): If set the alpha channel of the input image will be taken into account, 
  and pixels with alpha < 127 will not be drawn. For image types without explicit alpha channel, 
  the color (0, 0, 1) (very dark blue) will be mapped to black, to be able to store transparency information 
  within the image. Explicitly transparent types (``TRANSPARENT_BINARY`` and ``RGBA``) default to ``true`` and cannot be set to ``false``; other types default to ``false``.
```

2024-08-06 11:07 UTC, jesserockz approved these changes

2024-08-06 11:08 UTC, merged