Updates for new functionality of the EZO component.
OttoWinter/esphomedocs pull request #2133
Opened 2022-06-14 18:35 UTC by gvdhoven

## Description:

Updated docs for ezo PR

**Related issue (if applicable):** fixes N/A

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [X] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [X] Link added in `/index.rst` when creating new documents for new components or cookbook.

2022-06-19 18:47 UTC, Assunto commented
@gvdhoven  I'm trying to set this up and am hitting a confusing snag because the example code from #3561 suggests the way to talk to the sensors is through mqtt where the #2133 deploy preview page makes me think you do it through lambdas? I'm not very good at either.

Would you mind explaining which method to use and a super simple tutorial on getting it set up?

2022-06-27 12:38 UTC, gvdhoven commented
> @gvdhoven I'm trying to set this up and am hitting a confusing snag because the example code from #3561 suggests the way to talk to the sensors is through mqtt where the #2133 deploy preview page makes me think you do it through lambdas? I'm not very good at either.
> 
> Would you mind explaining which method to use and a super simple tutorial on getting it set up?

That is out of scope of this PR to be honest..

2022-09-21 19:08 UTC, Assunto commented
Is there a reason why this wasn't included in today's esphome update?

2022-09-24 13:00 UTC, jkeys1989 commented
> [<img alt="@Assunto" width="20" height="20" src="https://avatars.githubusercontent.com/u/100805744?s=40&amp;v=4">](/Assunto) [Assunto](/Assunto) mentioned this pull request [ on Jun 19 ](#ref-pullrequest-1261118784)

I was wondering the same.

2022-10-19 20:09 UTC, jncanches commented
Will this PR be included in next release ?
Calibration is a very great update ! Thanks !

2022-10-20 12:03 UTC, jkeys1989 commented
> Will this PR be included in next release ? Calibration is a very great update ! Thanks !

I'm currently using this like. .. 

works perfect. 

external_components:
  - source: github://pr#3561
    components: [ ezo ]

sensor:

  - platform: ezo
    id: ph_ezo
    address: 99
    accuracy_decimals: 2
    name: "PH Sensor"
    unit_of_measurement: "pH"
    update_interval: 10s

button:

  - platform: template
    name: "Cal 7 PH"
    on_press:
        lambda: !lambda |-
           id(ph_ezo).send_custom("cal,mid,7");

  - platform: template
    name: "Cal 4 PH"
    on_press:
        lambda: !lambda |-
           id(ph_ezo).send_custom("cal,low,4");

  - platform: template
    name: "Cal 10 PH"
    on_press:
        lambda: !lambda |-
           id(ph_ezo).send_custom("cal,high,10");

  - platform: template
    name: "ph led on"
    on_press:
        lambda: !lambda |-
           id(ph_ezo).send_custom("L,1");

2022-11-08 19:06 UTC, jesserockz requested changes

2022-11-08 19:06 UTC, jesserockz commented on components/sensor/ezo.rst
> +If a certain command is not supported by default, it can be executed with
Stopped mid sentence?

2022-11-08 19:06 UTC, jesserockz commented on components/sensor/ezo.rst
> +- **on_custom:** : Triggered when the result of ``get_custom()`` is ready
These should be part of the above configuration variables list in the correct format.

2022-11-09 22:06 UTC, jesserockz approved these changes

2022-11-09 22:07 UTC, merged