Max6956 support added
OttoWinter/esphomedocs pull request #2138
Opened 2022-06-16 13:40 UTC by looping40

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#3570

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2022-08-01 23:02 UTC, DrunkPyromaniac requested changes
Looks good, except for the minor details.

2022-08-01 23:02 UTC, GregJArnold commented on components/max6956.rst
> +and can therefore be used with many of ESPHome's components such as the GPIO binary sensor or GPIO switch. Interrupt-on-change for inputs is not currently implemented.
It looks like, as far as I can tell reading the datasheet, that the MAX6956 doesn't have the ability to generate an interrupt per se, so I would say instead "Interrupt-on-change for inputs is not possible.", as your wording implies that it would be possible in the future.  The transition detection feature does exist, but it still requires the master to read a register on the chip, so it's not really what's traditionally considered a pin-change interrupt.

2022-08-01 23:02 UTC, GregJArnold commented on components/max6956.rst
> +- All other options from Binary Sensor.
Can you link this to the Binary Sensor page?

2022-08-01 23:02 UTC, GregJArnold commented on components/max6956.rst
> +- **number** (**Required**, int): The pin number.
I'd specify the range here - "Must be in the range from 4 to 31."

2022-08-01 23:02 UTC, GregJArnold commented on components/max6956.rst
> +Pins can also be individualy configured as led driver and used with Light components. Current value can be set globaly or for each pin, through 16 possible levels.Driving RGB
Nitpick, but you need a space before "Driving".

2022-09-02 12:09 UTC, nagyrobi reviewed
Missing a tick after `binary_sensor/gpio`

2022-09-18 19:30 UTC, jesserockz commented
As this is a feature matched with a PR in `esphome/esphome`, please target your PR to the `next` branch and rebase.

Thanks
Jesse

2022-09-23 13:07 UTC, looping40 commented
Replaced by https://github.com/esphome/esphome-docs/pull/2320 as I created this PR on "current" branch instead of "next"

2022-09-23 13:07 UTC, closed without merging