Add smt100 doc
OttoWinter/esphomedocs pull request #2197
Opened 2022-07-24 13:35 UTC by piechade

## Description:
Documentation for the new smt100 component.

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2022-07-24 20:22 UTC, jesserockz requested changes

2022-07-24 20:22 UTC, jesserockz commented on index.rst
> +    SMT100, components/sensor/smt100, smt100.jpg, Moisture &Temperature
```suggestion
    SMT100, components/sensor/smt100, smt100.jpg, Moisture & Temperature
```

2022-07-24 20:22 UTC, jesserockz commented on components/sensor/smt100.rst
> +The communication with this integration is done over a UART bus using a simple ASCII protocol. You must therefore have a uart: entry in your configuration with both the TX and RX pins set to some pin
```suggestion
The communication with this integration is done over a UART bus using a simple ASCII protocol. You must therefore have a ``uart:`` entry in your configuration with both the TX and RX pins set to some pins on your board and the baud rate set to 9600.
```

2022-07-26 06:50 UTC, piechade reviewed
Looks good from my side.

2022-07-27 21:18 UTC, piechade commented
@jesserockz what's missing for a merge? Both changes requests are done.

2022-07-27 21:30 UTC, jesserockz commented
> what's missing for a merge?

Patience =)

2022-07-27 22:45 UTC, piechade commented
> > what's missing for a merge?
> 
> Patience =)

Ok, I was concerned about the wrong accepted request from you. I was not sure if my work is done correctly.

2022-07-27 23:21 UTC, jesserockz approved these changes

2022-07-27 23:22 UTC, merged