Update xpt2046 documentation
OttoWinter/esphomedocs pull request #2259
Opened 2022-09-02 00:51 UTC by nielsnl68

## Description:
- removed the binary_sensor information. use the touchscreen version
- removed the now unused keys
- renamed irq_pid into interupt_pin

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#3755

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2022-09-14 23:56 UTC, jesserockz requested changes
Please add a redirect in `/_redirects`

2022-09-15 06:53 UTC, nielsnl68 commented
> Please add a redirect in `/_redirects`

sorry, can you tell me exactly what i need to do?

2022-09-20 19:15 UTC, jesserockz commented on _redirects
> +/components/binary_sensor/xpt2046 /components/touchscreen/xpt2046 301
```suggestion
/components/binary_sensor/xpt2046.html /components/touchscreen/xpt2046.html 301
```

2022-10-10 21:09 UTC, jesserockz approved these changes

2022-10-10 21:10 UTC, merged