Add information about 3.3v current ability and UART rx_buffer_size
OttoWinter/esphomedocs pull request #2281
Opened 2022-09-09 12:09 UTC by codewise-nicolas

Added two paragraphs in the uart pinout section about 3.3v current sourcing on the bms, and about uart buffer size problems and fix.

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2022-09-23 23:44 UTC, codewise-nicolas commented
If this addition is not wanted, decline my PR!

2022-09-30 04:48 UTC, nagyrobi commented
@codewise-nicolas patience...

2022-10-30 03:00 UTC, jesserockz requested changes

2022-10-30 03:00 UTC, jesserockz commented on components/sensor/daly_bms.rst
> +On the ESP32 (untested on ESP8266) if you are having missing data (such as Temperatur 1/2), it may be due to UART buffer size.
```suggestion
On the ESP32 (untested on ESP8266) if you are having missing data (such as Temperature 1/2), it may be due to UART buffer size.
```

2022-10-30 03:00 UTC, jesserockz commented on components/sensor/daly_bms.rst
> +
```suggestion
.. code-block:: 

    uart: 
      ...
      rx_buffer_size: 512

```

2022-11-01 17:07 UTC, codewise-nicolas commented
@jesserockz thanks for the suggestions, ive accepted/commited them to the pr.

2022-11-09 19:00 UTC, jesserockz approved these changes

2022-11-09 19:00 UTC, merged