BP5758D - Initial documentation for BP5758D LED driver.
OttoWinter/esphomedocs pull request #2433
Opened 2022-11-12 17:52 UTC by Cossid

## Description:
Add documentation for new component BP5758D LED driver

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#4021

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2022-11-12 18:01 UTC, Cossid commented
Note to reviewer: CI hit a network timeout, I cannot trigger a new run without a commit.  It will still lead to a lint failure because of a reference link to another document also in PR.

2022-12-08 22:07 UTC, jesserockz requested changes

2022-12-08 22:07 UTC, jesserockz commented on components/output/bp5758d.rst
> +- :doc:`/components/output/bp1658cj`
The site wont actually build with this error. You can add this link in the second PR as I will merge this one first
```suggestion
```

2022-12-08 22:07 UTC, jesserockz commented on components/output/bp5758d.rst
> +        current: 10 # In mA, valid values 0-90, default 10
This example should only have the hub code, then below is a single float output. 
If you want to have a full example for a specific bulb, it should go down the bottom above `see also`
```suggestion
```

2022-12-08 22:07 UTC, jesserockz commented on components/output/bp5758d.rst
> +        current: 10 # In mA, valid values 0-90, default 10
```suggestion
    # Example configuration entry
    output:
      - platform: bp5758d
        id: output_red
        channel: 2 # Valid values 1-5 to match OUT1-OUT5
        current: 10 # In mA, valid values 0-90, default 10
```

2022-12-08 22:14 UTC, jesserockz commented
Haha, I just realised you have another PR for the `sm2335` as well. Maybe remove all crosslinking between the pages in the PRs and make one more PR that links them once they are all merged. (Small PRs with no dependencies are easy to merge :smile:)

2022-12-08 22:16 UTC, Cossid commented
Yeah, I have 3 LED drivers in queue (BP5758D, BP1658CJ, and SM2335/SM2235).  I'll unlink them from each other in docs shortly.

2022-12-22 21:24 UTC, jesserockz approved these changes

2022-12-22 21:24 UTC, merged