Update mopeka_pro_check component docuentation to support Lippert devices
OttoWinter/esphomedocs pull request #2493
Opened 2022-11-29 15:36 UTC by rperciaccante

## Description:
Update mopeka_pro_check component to include Lippert device information to support PR

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#[<esphome PR number goes here>](https://github.com/esphome/esphome/pull/4118)

## Checklist:

  - [ X] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ X] Link added in `/index.rst` when creating new documents for new components or cookbook.

2022-11-30 03:42 UTC, jesserockz requested changes
Please move references to Lippert to *after* the original Mopeka wording.

2022-11-30 03:55 UTC, jesserockz commented
As this is a feature matched with a PR in `esphome/esphome`, please target your PR to the `next` branch and rebase.

Thanks
Jesse

2022-11-30 18:48 UTC, rperciaccante commented
> Please move references to Lippert to _after_ the original Mopeka wording.
Completed

2023-02-08 22:07 UTC, jesserockz approved these changes

2023-02-08 22:07 UTC, merged