Add graphical display menu docs
OttoWinter/esphomedocs pull request #2572
Opened 2023-01-03 11:27 UTC by MrMDavidson

## Description:

Adds documentation for the new Graphical Display Menu.

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#4105

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2023-01-03 11:29 UTC, MrMDavidson commented
Note: Currently using the same images in the index image table, and documentation, as the `lcd_menu`.

2023-07-30 23:00 UTC, jesserockz requested changes
Can you please slim down the configuration example. I had a look at the LCD menu example and its also quite big (not to be changed here) but the main example at the top should be a simple minimum yaml for this component only, and if you want to have more full examples, they should be at the bottom of the page, after all of the yaml actions have also be added.

2023-07-30 23:24 UTC, MrMDavidson commented
> Can you please slim down the configuration example. I had a look at the LCD menu example and its also quite big (not to be changed here) but the main example at the top should be a simple minimum yaml for this component only, and if you want to have more full examples, they should be at the bottom of the page, after all of the yaml actions have also be added.

Can do! I need to revisit this PR to add documentation on pop up vs advanced drawing mode in light of the changes in the linked PR. Will do them all together once we're good with the design changes.

2023-12-12 03:07 UTC, jesserockz requested changes

2023-12-12 03:07 UTC, jesserockz commented on components/display_menu/graphical_display_menu.rst
> +engine such as :doc:`E-Paper displays <../display/waveshare_epaper>` or :doc:`OLED displays <../display/ssd1306>`.
Docs should be absolute, or relative only if in the same directory
```suggestion
engine such as :doc:`E-Paper displays </components/display/waveshare_epaper>` or :doc:`OLED displays </components/display/ssd1306>`.
```

2023-12-12 03:09 UTC, jesserockz approved these changes

2023-12-12 03:16 UTC, merged