Add docs for Grove Multichannel Gas Sensor V2
OttoWinter/esphomedocs pull request #2598
Opened 2023-01-16 22:46 UTC by YorkshireIoT

## Description:

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2023-02-23 01:08 UTC, jesserockz requested changes

2023-02-23 01:08 UTC, jesserockz commented on components/sensor/grove_gas_mc_v2.rst
> +      scl: D1
No board specific pins here please. Use `GPIO` numbers or remove the i2c section as it is already stated above as a requirement.

2023-02-23 01:08 UTC, jesserockz commented on components/sensor/grove_gas_mc_v2.rst
> +  - All other options from :ref:`Sensor <config-sensor>`.
No need to specify what is already in the sensor config section linked. This way "forces" people to learn the sensor core config better =)

Same for the rest please.

```suggestion
- **no2** (**Required**): The Nitrogen Dioxide sensor data. All options from :ref:`Sensor <config-sensor>`.
```

2023-04-27 05:56 UTC, YorkshireIoT commented
> There hasn't been any activity on this pull request recently. This pull request has been automatically marked as stale because of that and will be closed if no further activity occurs within 7 days. Thank you for your contributions.

Waiting on review

2024-02-20 06:47 UTC, YorkshireIoT commented
Ping

2024-04-21 09:53 UTC, YorkshireIoT commented
Not stale

2024-06-22 08:54 UTC, YorkshireIoT commented
Not stale

2024-08-22 07:48 UTC, YorkshireIoT commented
Not stale

2024-10-07 01:17 UTC, jesserockz commented on components/sensor/grove_gas_mc_v2.rst
> +        update_interval: 60s
Not needed
```suggestion
```

2024-10-07 01:17 UTC, jesserockz approved these changes

2024-10-07 02:34 UTC, merged