add person sensor (sen21231) from useful sensors
OttoWinter/esphomedocs pull request #2678
Opened 2023-02-17 02:02 UTC by shreyaskarnik

## Description:

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/1925

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2023-02-17 06:19 UTC, jesserockz commented
As this is a feature matched with a PR in `esphome/esphome`, please target your PR to the `next` branch and rebase.

Thanks
Jesse

2023-02-17 06:45 UTC, shreyaskarnik commented
Thanks, for the feedback @jesserockz I updated the target branch and rebased but could not fix the change in `_static/version`. Happy to add a new PR for the docs. Apologies about targeting the current branch did not know about the next branch.

2023-02-20 04:04 UTC, jesserockz requested changes

2023-02-20 04:04 UTC, jesserockz commented on components/sensor/sen21231.rst
> +    output:
This is a sensor, not an output...
```suggestion
    sensor:
```

2023-02-20 04:04 UTC, jesserockz commented on components/sensor/sen21231.rst
> +        # power connected to 3.3v
We don't need extra comments here when this information is contained in the i2c docs.
```suggestion
```

2023-02-20 04:04 UTC, jesserockz commented on components/sensor/sen21231.rst
> +This sensor returns information over I2C interface. The I2C address is ``0x62``
```suggestion
This sensor requires an :doc:`/components/i2c`. The I2C address is ``0x62``
```

2023-02-20 04:18 UTC, shreyaskarnik commented
@jesserockz thanks for the suggestions I have applied them. I appreciate your help. 🙌

2023-02-23 00:33 UTC, jesserockz approved these changes

2023-02-23 00:37 UTC, merged