add emc2101 component
OttoWinter/esphomedocs pull request #2709
Opened 2023-02-26 22:32 UTC by ellull

## Description:

Adds EMC2101 component documentation.

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#4491

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2023-06-10 08:26 UTC, ellull commented
Waiting for the parent PR esphome/esphome#4491 to be merged.

2023-10-23 23:49 UTC, jesserockz requested changes

2023-10-23 23:49 UTC, jesserockz commented on components/emc2101.rst
> +        update_interval: 5s
This main example should only apply to the main component. 
`sensor` and `output` have their own yaml sections below and we dont need to repeat them here.

If you want to have a full example, please make it the last item on the page in its own section.


```suggestion
.. code-block:: yaml

    # Example configuration entry
    emc2101:
      pwm:
        resolution: 8
```

2023-10-23 23:49 UTC, jesserockz commented on components/emc2101.rst
> +- **pwn** (*Optional*): Enable PWN output.
```suggestion
- **pwm** (*Optional*): Enable PWM output.
```

2023-10-23 23:49 UTC, jesserockz commented on components/emc2101.rst
> +sensors and a tachometer. The fan can be controlled either by a PWN signal or by outputing a DC voltage
```suggestion
sensors and a tachometer. The fan can be controlled either by a PWM signal or by outputing a DC voltage
```

2023-10-23 23:49 UTC, jesserockz commented on components/emc2101.rst
> +The PWN signal frequency is determined by the following formula:
```suggestion
The PWM signal frequency is determined by the following formula:
```

2023-10-23 23:49 UTC, jesserockz commented on components/emc2101.rst
> +  - All other options from :ref:`Sensor <config-sensor>`.
This is already defined in the linked sensor config for users to read and learn.
```suggestion
- **internal_temperature** (*Optional*): The internal temperature sensor. 
  All options from :ref:`Sensor <config-sensor>`.
```

2023-10-23 23:49 UTC, jesserockz commented on components/emc2101.rst
> +  - All other options from :ref:`Sensor <config-sensor>`.
```suggestion
- **external_temperature** (*Optional*): The external temperature sensor. More accurate but it needs an additional transistor to be installed. 
  All options from :ref:`Sensor <config-sensor>`.

- **speed** (*Optional*): The fan speed sensor in RPMs. 
  All options from :ref:`Sensor <config-sensor>`.

- **duty_cycle** (*Optional*): Duty cycle sensor. 
  All options from :ref:`Sensor <config-sensor>`.
```

2023-10-23 23:50 UTC, jesserockz requested changes
YOu also have not added an entry on the root `index.rst` file, so it will not show up in the tables on the homepage.

2023-10-25 18:29 UTC, jesserockz approved these changes

2023-10-25 18:30 UTC, merged