Add documentation for fs3000 sensor.
OttoWinter/esphomedocs pull request #2715
Opened 2023-03-03 13:54 UTC by kahrendt

## Description:

This pull request adds documentation and images for the fs3000 air velocity sensor.

**Related issue (if applicable):** not applicable

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2023-03-06 07:03 UTC, jesserockz requested changes
Please at a minimum add a see also with the edit link to the bottom of the page

```rst
See Also
--------

- :ghedit:`Edit`
```

2023-03-06 07:03 UTC, jesserockz commented on components/sensor/fs3000.rst
> +- **update_interval** (*Optional*, :ref:`config-time`): The interval to check the sensor. Defaults to ``60s``.
```suggestion
- **model** (**Required**, string): Specify FS3000 model, can be ``1005`` or ``1015``.
- **address** (*Optional*, int): Manually specifiy the I²C address of the sensor. Defaults to ``0x28``.
- **update_interval** (*Optional*, :ref:`config-time`): The interval to check the sensor. Defaults to ``60s``.
- All other options from :ref:`Sensor <config-sensor>`.
```

2023-03-06 13:14 UTC, kahrendt commented
Thank you for the feedback! I removed the configuration id bullet and added the see also section with an edit command.

2023-03-07 04:12 UTC, jesserockz approved these changes

2023-03-07 06:27 UTC, merged