Add pylontech integration
OttoWinter/esphomedocs pull request #2841
Opened 2023-04-14 22:37 UTC by functionpointer

## Description:

Adds documentation for the new pylontech integration.

**Related issue (if applicable):** none

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#4688

## Checklist:

  - [X] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [X] Link added in `/index.rst` when creating new documents for new components or cookbook.

2023-07-30 05:58 UTC, functionpointer commented
Not stale, parent is just still pending after 2 months with no response

2023-11-27 22:13 UTC, jesserockz requested changes

2023-11-27 22:13 UTC, jesserockz commented on components/pylontech.rst
> +Configuration
```suggestion
Component/Hub
```

2023-11-27 22:13 UTC, jesserockz commented on components/pylontech.rst
> +
We don't add external examples here. It is up to the user to visit the uart docs to see how to configure that for their use case.
```suggestion
    # Example configuration entry
```

2023-11-27 22:13 UTC, jesserockz commented on components/pylontech.rst
> +        update_interval: 5s
Examples only needs the most basic configuration required.
```suggestion
    pylontech:
```

2023-11-27 22:13 UTC, jesserockz commented on components/pylontech.rst
> +        pylontech_id: pylontech0
When the example is used with only one component this is not needed
```suggestion
```

2023-11-27 22:13 UTC, jesserockz commented on components/pylontech.rst
> +          name: "Battery1 State of Charge"
```suggestion
        voltage:
          name: "Battery1 Voltage"
        current:
          name: "Battery1 Current"
        coulomb:
          name: "Battery1 State of Charge"
```

2023-11-27 22:13 UTC, jesserockz commented on components/pylontech.rst
> +          name: "Battery2 State of Charge"
```suggestion
```

2023-11-27 22:13 UTC, jesserockz commented on components/pylontech.rst
> +- **pylontech_id** (**Required**): ID of the pylontech instance
```suggestion
- **pylontech_id** (*Optional*): Manually specify the ID of the pylontech instance if there are multiple.
```

2023-11-27 22:13 UTC, jesserockz commented on components/pylontech.rst
> +- **battery** (**Required**): Which battery to monitor. 1 stands for the master battery, 2..6 for slave batteries.
We try not to use master/slave terms
```suggestion
- **battery** (**Required**): Which battery to monitor. 1 stands for the main battery, 2..6 for child batteries.
```

2023-11-27 22:13 UTC, jesserockz commented on components/pylontech.rst
> +- **voltage** (*Optional*): Voltage. Should be around 48V
Also needs to apply to the following sensors and similar for text sensors.
```suggestion
- **voltage** (*Optional*): Voltage of the battery. All options from :ref:`Sensor <config-sensor>`.
```

2023-11-27 22:13 UTC, jesserockz commented on components/pylontech.rst
> +All sensors are normal sensors, so each one supports options from :ref:`Sensor <config-sensor>`.
Inline is better as it shows up with code completion dialogs
```suggestion
```

2023-11-27 22:42 UTC, jesserockz approved these changes
Thanks @functionpointer

2023-11-27 22:43 UTC, merged