Document W5500 support
OttoWinter/esphomedocs pull request #2843
Opened 2023-04-15 11:19 UTC by JeroenVanOort

## Description:

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/1235

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#4424

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2023-08-23 23:17 UTC, DjordjeMandic commented
Does `Optional manual IP` work with SPI chips also?

2023-11-05 09:21 UTC, JeroenVanOort commented
> Does `Optional manual IP` work with SPI chips also?

Yes, but I haven't tested recently.

2023-12-04 23:40 UTC, jesserockz requested changes

2023-12-04 23:40 UTC, jesserockz commented on components/ethernet.rst
> +- **mdc_pin** (**Required for RMII chips**, :ref:`config-pin`): The MDC pin of the board.
We have scripts that are specifically looking for `**Required**` or `*Optional*` in this section.
Perhaps it is better to split the common schema and the RMII and SPI schemas into their own lists? 

```suggestion
- **mdc_pin** (**Required for RMII chips**, :ref:`config-pin`): The MDC pin of the board.
```

2024-03-01 00:44 UTC, jesserockz approved these changes

2024-03-01 00:46 UTC, merged