add lightwave
OttoWinter/esphomedocs pull request #2915
Opened 2023-05-12 20:13 UTC by max246

## Description:

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#4812

## Checklist:

  - [ x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2023-05-13 09:18 UTC, kbx81 requested changes
Suggestions to fix a few typos and also please double-check that what you have documented matches _exactly_ what is expected by the configuration validation. 🙂

2023-05-13 09:18 UTC, kbx81 commented on components/light/lightwaverf.rst
> +:ref:`float output component <output>`.
You're referring to an output component here but I don't see that anywhere in the configuration. Is this a copy/paste error?

2023-05-13 09:18 UTC, kbx81 commented on components/light/lightwaverf.rst
> +Using cheap RF receiver and transmitter you can implemented a simple implementation to control your devices.
```suggestion
LightwaveRF switches are very common in UK automation. They allow control of lights, sockets, relays and more via RF remote
 or via a hub.
Using an inexpensive RF transmitter and receiver you can control your devices via ESPHome.
```

2023-05-13 09:18 UTC, kbx81 commented on components/light/lightwaverf.rst
> +- **write_pin** (**Required**, string): Internal Pin that the transmitter is connected to
These are not `int` or `string` parameters. They refer to pin schemas.

```suggestion
- **read_pin** (**Required**, :ref:`Pin Schema <config-pin_schema>`): The pin that the receiver is connected to
- **write_pin** (**Required**, :ref:`Pin Schema <config-pin_schema>`): the pin that the transmitter is connected to
```

2023-05-13 09:18 UTC, kbx81 commented on components/light/lightwaverf.rst
> +-------------------------------
```suggestion
Configuration variables:
------------------------
```

2023-05-13 09:18 UTC, kbx81 commented on components/light/lightwaverf.rst
> +- **id** (**Required**, :ref:`config-id`): The id of the switch to call via HA
I'm not sure what this section is for...can probably delete it

2023-05-13 09:18 UTC, kbx81 commented on components/light/lightwaverf.rst
> +- **invert** (*Optional*, int): Send the signal inverted
So it matches what you have in the schema 😉

```suggestion
- **inverted** (*Optional*, boolean): Send the signal inverted
```

2023-05-23 06:38 UTC, kbx81 requested changes
Couple more suggestions 😇

2023-05-23 06:38 UTC, kbx81 commented on components/light/lightwaverf.rst
> +These are the sensors which are been confirmed to work with the current code base, if you use different onces and they work, please report them to the team.
```suggestion
The RF transmitters/receivers listed below have been confirmed to work with the current code base. If you discover others that work, please let us know!
```

2023-05-23 06:38 UTC, kbx81 commented on components/light/lightwaverf.rst
> +------------------
```suggestion
Compatible Hardware
-------------------
```

2023-07-12 20:55 UTC, jesserockz commented on components/light/lightwaverf.rst
> +- **id** (**Required**, :ref:`config-id`): The id of the switch to call via HA
Copy pasted from somewhere?
```suggestion
```

2023-07-12 21:58 UTC, kbx81 requested changes

2023-07-12 21:58 UTC, kbx81 commented on components/light/lightwaverf.rst
> +- **repeat** (*Optional*, int): The amount of repeats to send the signal
This reads strangely. How about this?
```suggestion
- **repeat** (*Optional*, int): The number of times the message will be repeated
```

2023-09-05 22:23 UTC, jesserockz commented on components/light/lightwaverf.rst
> +- :doc:`/components/output/esp8266_pwm`
I don't think this is really relevant to this component...
```suggestion
```

2023-09-05 22:24 UTC, jesserockz commented on index.rst
> +    Custom Light, components/light/custom, language-cpp.svg
```suggestion
    Custom Light, components/light/custom, language-cpp.svg, dark-invert
```

2023-09-05 22:24 UTC, jesserockz approved these changes

2023-09-05 22:33 UTC, merged