Documentation for WireGuard component and sensors
OttoWinter/esphomedocs pull request #2948
Opened 2023-05-27 05:59 UTC by droscy

## Description:

This is the documentation for WireGuard Component and its two sensors: WireGuard Status and WireGuard Latest Handshake.

It takes into account all the features in PR lhoracek/esphome#9 that will be merged in esphome/esphome#4256 as soon as possible.

I have created a custom logo for the index page because the official logo is a registered trademark and cannot be used for custom implementation.

**Related issue (if applicable):**
- original feature request esphome/feature-requests#1444

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#4256

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  

  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2023-08-16 05:09 UTC, droscy commented
This is not stale, the doc is still valid.

2023-08-20 22:23 UTC, jesserockz requested changes
Docs for parent/child sensors actually mostly live on the same page (the parent page). There are a few exmaples of this, but search for Component/Hub in the docs codebase.

There can still be multiple index links to the same page.

2023-08-20 22:23 UTC, jesserockz commented on .gitignore
Please dont make changes unrelated to wireguard

2023-08-20 22:23 UTC, jesserockz commented on Makefile
Please dont make changes unrelated to wireguard

2023-08-21 05:19 UTC, droscy commented on Makefile
My mistake, sorry, I'll revert it.

2023-08-21 05:23 UTC, droscy commented on .gitignore
I have excluded Eclipse project files and of course I can revert it. But could you please exclude them on your next commit to `next` branch?

2023-08-21 05:34 UTC, droscy commented
> There are a few exmaples of this, but search for Component/Hub in the docs codebase.
> There can still be multiple index links to the same page.

@jesserockz I am not sure to fully understand what you asked... should I simply add a "Component/Hub" section at the same level of "Sensor" section?

2023-08-21 05:47 UTC, nagyrobi commented
Put all wireguard-related doc in one rst file. No separate files for parent component and child sensors.

2023-08-21 06:32 UTC, droscy commented
It is already in a single page, everything is here https://deploy-preview-2948--esphome.netlify.app/components/wireguard

2023-08-21 06:36 UTC, nagyrobi commented
This PR still shows that there are several other files involved in the change. Look at the _Files Changed_ tab.

I suggest to either rebase, or close and resubmit the PR freshly.

2023-08-21 06:44 UTC, droscy commented
> This PR still shows that there are several other files involved in the change. Look at the _Files Changed_ tab.

Ops, I left them there. I'll remove them.

> There are also conflicts to be fixed.

Because the last commit here was 2 months ago...

2023-09-06 05:09 UTC, jesserockz approved these changes

2023-09-11 19:13 UTC, merged