Add WeiKai component documentation
OttoWinter/esphomedocs pull request #3113
Opened 2023-08-08 14:10 UTC by DrCoolzic

Documentation for the new Weikai family of components

## Description:
This component adds support for the Weikai family of component chips. It add the following components:
wk2132_spi, wk2212_spi, wk2204_spi, wk2168_spi, wk2132_i2c, wk2212_i2c, wk2204_i2c, wk2168_i2c

The code for the component has been submitted with the PR #5218

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#5218
Add WK2132 component to esphome #5218
## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2023-08-08 14:16 UTC, DrCoolzic commented
PR for code
Add WK2132 component to esphome #5218

2023-12-19 02:43 UTC, jesserockz requested changes

2023-12-19 02:43 UTC, jesserockz commented on components/wk2132_i2c.rst
> +buffers for transmission and reception.
Until such a time as that component exists, it is best not to document it as existing...
```suggestion
The WK2132 chip/module serves as an I²C to Dual UART converter, supporting data transmission rates 
of up to 1 Mbps. Each UART channel features two independent 256-byte FIFO hardware 
buffers for transmission and reception.
```

2023-12-19 02:43 UTC, jesserockz commented on components/wk2132_i2c.rst
> +
This limitation will be fixed before the component is merged.
```suggestion
```

2023-12-19 02:43 UTC, jesserockz commented on components/wk2132_i2c.rst
> +- :ghedit:`Edit`
```suggestion
- :apiref:`wk2132_i2c/wk2132_i2c.h`
- :ghedit:`Edit`
```

2023-12-19 02:43 UTC, jesserockz commented on components/wk2132_i2c.rst
> +**********************************
```suggestion
Configuration variables:
************************
```

2023-12-20 11:22 UTC, kbx81 commented on components/wk2132_i2c.rst
> +
Typically we don't include the configuration of dependent components in the example.
```suggestion
```

2024-01-03 18:13 UTC, DrCoolzic commented
Sorry as the PR was still open I took the oportunity to squeeze the SPI version as well :)

2024-02-28 12:51 UTC, nagyrobi commented
@DrCoolzic can you please check if @jesserockz 's observations are still valid or not, and resolve them if necessarry? (if already resolved, mark them as resolved please)

2024-02-28 14:15 UTC, DrCoolzic commented
> @DrCoolzic can you please check if @jesserockz 's observations are still valid or not, and resolve them if necessarry? (if already resolved, mark them as resolved please)

I beleive I have now marked the request as resolved. I had to made a change to my rst file based on feedback from @jesserockz and I just pushed it few minutes ago

2024-04-10 15:06 UTC, DrCoolzic commented
Modified the documentation to reflect changes required by @jesserockz to uart_id
Plus miscellaneous spelling correction

2024-04-24 01:20 UTC, jesserockz approved these changes

2024-04-24 01:21 UTC, merged