FastLED documentation update for esphome/esphome#4257
OttoWinter/esphomedocs pull request #3148
Opened 2023-08-21 04:33 UTC by bibach

## Description:

Update FastLED documentation to reflect new, unified _fastled_ component and indicate that the existing, separate components are now deprecated.

**Related issue (if applicable):** 

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#4257

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2023-08-21 23:47 UTC, nielsnl68 requested changes
Thanks for changing the document for me. I have some small changing suggestions added below/

2023-08-21 23:47 UTC, nielsnl68 commented on components/light/fastled.rst
> +      - platform: fastled_clockless
```suggestion
      - platform: fastled
```

2023-08-21 23:47 UTC, nielsnl68 commented on components/light/fastled.rst
> +      - platform: fastled_spi
```suggestion
      - platform: fastled
```

2023-08-21 23:47 UTC, nielsnl68 commented on components/light/fastled.rst
```suggestion
```

My suggestion is moving the warning to the top and remove this sections.

2023-08-21 23:47 UTC, nielsnl68 commented on components/light/fastled.rst
> +
```suggestion

.. warning::

    The ``fastled_spi`` and the ``fastled_clocless`` light platform are now deprecated.  
    Use the new, unified ``fastled`` light platform, instead.
```
My suggestion is to move the warning from the bottom of this document to here and remove the section about the ``fastled_spi`` and the ``fastled_clocless``.

2023-08-22 00:13 UTC, bibach commented
Good catch about the platform names in the examples.  Meant to update those after copying them from the other sections.

I hesitated on removing the existing material, as I wasn't sure if you intended to deprecate the other components.  If you're good to proceed with that, sounds good to me.

2023-10-24 22:38 UTC, nielsnl68 commented
Still waiting for the esphome-PR to be merged

2024-03-11 02:03 UTC, nielsnl68 commented
'ping

2024-07-07 01:50 UTC, closed without merging