Remove enable_ipv6 restricted to ESP32 with ESP-IDF
OttoWinter/esphomedocs pull request #3190
Opened 2023-09-16 17:48 UTC by Nardol

## Description:

Now esphome/esphome#4759, esphome/esphome#4865 and esphome/esphome#4976 are merged, enable_ipv6 should be used without restriction.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [x] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2023-09-18 17:45 UTC, HeMan approved these changes, later dismissed

2023-09-19 10:22 UTC, jesserockz requested changes
As this is a feature matched with a PR in `esphome/esphome`, please target your PR to the `next` branch and rebase.

Thanks
Jesse

2023-09-19 11:08 UTC, Nardol commented
Sorry, rebase and target with `next` done.

2023-09-20 22:18 UTC, jesserockz approved these changes

2023-09-20 22:18 UTC, merged