Tuya Number: split "multiply" to a separate option
OttoWinter/esphomedocs pull request #3224
Opened 2023-10-01 14:46 UTC by paravoid

## Description:

Commit a4ba7f3 (PR #3075), adjusted the documentation for Tuya Number, to represent the "step" attribute adjusting the multiplication factor for Tuya Numbers.

This is now being changed, restoring the original functionality, and introducing a new "multiply" attribute for the same purpose. Adjust the documentation to represent this change.

**Related issue (if applicable):** 

Fixes: esphome/issues#4928

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#5458

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [x] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2023-10-02 22:28 UTC, jesserockz requested changes
As this is a feature matched with a PR in `esphome/esphome`, please target your PR to the `next` branch and rebase.

Thanks
Jesse

2023-10-03 00:14 UTC, paravoid commented
> As this is a feature matched with a PR in `esphome/esphome`, please target your PR to the `next` branch and rebase.

Thanks for the review, Jesse! I was unsure which branch to target, so that's helpful! Just for my own understanding, is "current" for (at this time) 2023.9.x point releases, and next for 2023.10.0?

The original Tuya Number scaling, that introduced the regression for `step`, was introduced between with 2023.9.1 (cherry-picked, I think?), so I was hoping this will get fixed in a 2023.9.x release. Does this matter?

2023-10-03 00:16 UTC, ssieb commented
`Current` is for fixes to existing docs.  Anything new goes in `next`.  I expect this will get into the next point release.

2023-10-03 00:20 UTC, jesserockz approved these changes

2023-10-03 00:23 UTC, merged