update doc
OttoWinter/esphomedocs pull request #3267
Opened 2023-10-14 10:33 UTC by max246

## Description:

Updated the information for the new method and ensure to provide examples how to setup multi boards

**Related issue (if applicable):** fixes  https://github.com/esphome/feature-requests/issues/2411

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#5492

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [x] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2023-10-14 23:20 UTC, simonyel commented
I tested the `github://pr#5492,` and it works as expected.

2023-10-15 02:51 UTC, simonyel reviewed
I tested the github://pr#5492, and it works as expected. I have two driver boards and 4 DC motors\peri-pumps. I was able to address and execute commands on each device. Start > Break >Stop.

2023-10-15 18:37 UTC, jesserockz requested changes
As this is a feature matched with a PR in `esphome/esphome`, please target your PR to the `next` branch and rebase.

Please also update your PR titles to at least mention the component that changes have been made for.

Thanks
Jesse

2023-10-15 19:20 UTC, max246 commented
> As this is a feature matched with a PR in `esphome/esphome`, please target your PR to the `next` branch and rebase.
> 
> Please also update your PR titles to at least mention the component that changes have been made for.
> 
> Thanks Jesse

thanks! Sorry about that

2023-10-15 22:24 UTC, jesserockz requested changes

2023-10-15 22:24 UTC, jesserockz commented on components/grove_tb6612fng.rst
> +
This whole example config should be smaller and only include the minimum required for getting the motor working. The rest is up to the user to read the documentation and write their config for their situation.

2023-10-15 22:24 UTC, jesserockz commented on components/grove_tb6612fng.rst
> +Set the board can change address in case you want to connect multiple once, the addresses avialable are: 0x01 ~ 0x7f
```suggestion
If you require connecting multiple boards at once, the address can be changed using this action. The address can be changed to a value in the range of ``0x01 - 0x7f`` inclusive.
```

2023-10-15 22:24 UTC, jesserockz commented on components/grove_tb6612fng.rst
> +        - grove_tb6612fng.change_address
```suggestion
        - grove_tb6612fng.change_address:
```

2023-10-16 19:47 UTC, jesserockz approved these changes

2023-10-16 19:47 UTC, merged