Add initial ld2450 document
OttoWinter/esphomedocs pull request #3327
Opened 2023-11-04 15:54 UTC by hareeshmu

## Description:

Add ld2450 documentation

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

https://github.com/esphome/esphome/pull/5674

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2025-02-10 05:19 UTC, kbx81 requested changes

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +The ``ld2450`` component allows you to use `HLK-LD2450 <https://www.hlktech.net/index.php?id=1157>`__ human presence and motion detection and tracking radar module with ESPHome.
```suggestion
The ``ld2450`` component allows you to use the `HLK-LD2450 <https://www.hlktech.net/index.php?id=1157>`__ human presence, motion detection and tracking radar module with ESPHome.
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +Motion target tracking involves real-time tracking of the position of a moving target within a specific area, enabling distance, angle, and speed measurements of the target.
```suggestion
Target tracking involves real-time tracking of the position of a (moving) target within a specific area, enabling measurement of the target's distance, angle and speed (relative to the sensor).
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +It is is mainly used in general indoor scenarios such as homes, offices and hotels to enable the location tracking of moving human targets.
```suggestion
It's primarily intended for use indoors to enable the location tracking of moving human targets.
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +
We do not include requisite component configuration in examples.

```suggestion
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +      uart_id: uart_ld2450
```suggestion
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +  to use multiple UART buses.
```suggestion
- **uart_id** (*Optional*, :ref:`config-id`): Manually specify the ID of the :ref:`UART Component <uart>` to use.
  Required if you have multiple UARTs configured.
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +- **id** (*Optional*, :ref:`config-id`): Manually specify the ID for this :doc:`ld2450` component if you need multiple components.
```suggestion
- **id** (*Optional*, :ref:`config-id`): Manually specify the ID for this :doc:`ld2450` component.
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +- **ld2450_id** (*Optional*, :ref:`config-id`): Manually specify the ID for the :doc:`ld2450` component if you are using multiple components.
```suggestion
- **ld2450_id** (*Optional*, :ref:`config-id`): Manually specify the ID for the :doc:`ld2450` component.
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +- **ld2450_id** (*Optional*, :ref:`config-id`): Manually specify the ID for the :doc:`ld2450` component if you are using multiple components.
```suggestion
- **ld2450_id** (*Optional*, :ref:`config-id`): Manually specify the ID for the :doc:`ld2450` component.
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +- **target_count** (*Optional*, int): Total targets detected, whether they are stationary or in motion..
```suggestion
- **target_count** (*Optional*, int): Total targets detected, whether they are stationary or in motion.
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +    - **target_count** (*Optional*, int): Total targets detected in the zone, whether they are stationary or in motion..
```suggestion
    - **target_count** (*Optional*, int): Total targets detected in the zone, whether they are stationary or in motion.
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +- **ld2450_id** (*Optional*, :ref:`config-id`): Manually specify the ID for the :doc:`ld2450` component if you are using multiple components.
```suggestion
- **ld2450_id** (*Optional*, :ref:`config-id`): Manually specify the ID for the :doc:`ld2450` component.
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +- **ld2450_id** (*Optional*, :ref:`config-id`): Manually specify the ID for the :doc:`ld2450` component if you are using multiple components.
```suggestion
- **ld2450_id** (*Optional*, :ref:`config-id`): Manually specify the ID for the :doc:`ld2450` component.
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +- **factory_reset** (*Optional*): "This command is used to reset the ``ld2450`` to its default values."
```suggestion
- **factory_reset** (*Optional*): Resets the ``ld2450`` to its factory default configuration/values.
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +- **ld2450_id** (*Optional*, :ref:`config-id`): Manually specify the ID for the :doc:`ld2450` component if you are using multiple components.
```suggestion

- **ld2450_id** (*Optional*, :ref:`config-id`): Manually specify the ID for the :doc:`ld2450` component.
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +    - **direction** (*Optional*): Direction of the target relative to the ``ld2450`` sensor. Possible values are: ``Stationary``, ``Moving away``, ``Coming closer``, ``NA``.
```suggestion
    - **direction** (*Optional*): Direction of the target relative to the ``ld2450`` sensor. Possible values are: ``Stationary``, ``Moving away``, ``Approaching``, ``NA``.
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +- **mac_address** (*Optional*): The ``ld2450`` Bluetooth mac address.
```suggestion
- **mac_address** (*Optional*): The ``ld2450`` Bluetooth MAC address.
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +-----------
```suggestion
------
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +- **ld2450_id** (*Optional*, :ref:`config-id`): Manually specify the ID for the :doc:`ld2450` component if you are using multiple components.
```suggestion
- **ld2450_id** (*Optional*, :ref:`config-id`): Manually specify the ID for the :doc:`ld2450` component.
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +      rx_pin: 21
```suggestion
      tx_pin: GPIOXX
      rx_pin: GPIOXX
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +
```suggestion
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +
```suggestion
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +    ota:
```suggestion
    ota:
      - platform: esphome
```

2025-02-10 05:19 UTC, kbx81 commented on components/sensor/ld2450.rst
> +
```suggestion
```

2025-02-18 14:13 UTC, WiebKastanje commented on components/sensor/ld2450.rst
> +- **multi_target** (*Optional*): Turn on/off the Multi Target Tracking option. All options from
defaults to ``off``

2025-02-19 00:07 UTC, kbx81 commented on components/sensor/ld2450.rst
> +- **multi_target** (*Optional*): Turn on/off the Multi Target Tracking option. All options from
Nope, it's read from the device at start-up so its state will depend on how it's set on the LD2450. IIRC, the LD2450's factory default has it set to "on", but the state is stored so it will be recalled after each reset or power-cycle.

2025-02-19 07:29 UTC, WiebKastanje commented on components/sensor/ld2450.rst
> +- **multi_target** (*Optional*): Turn on/off the Multi Target Tracking option. All options from
Yes, you are correct. Apologies for not fully understanding the LD2450 specs.

2025-02-19 07:43 UTC, kbx81 commented on components/sensor/ld2450.rst
> +- **multi_target** (*Optional*): Turn on/off the Multi Target Tracking option. All options from
Hmm, on the [bottom of page 9](https://make.net.za/wp-content/datasheets/HLK%20LD2450%20Serial%20Communication%20Protocol%20v1.03.pdf?srsltid=AfmBOor1m5z_I4GcYxlnqr5CAfEbDZlAn6-80BnC9HMDLzw4vO6Ob-Bj) it's indicated that multi-tracking is enabled by default.

2025-02-19 14:14 UTC, WiebKastanje commented on components/sensor/ld2450.rst
> +- **multi_target** (*Optional*): Turn on/off the Multi Target Tracking option. All options from
After factory reset, not only multi-target does not report back to default ON.
Also zone details like Zone Type (disabled) and Zone X and Y values (0 mm) do not report these default setting.
A Restart after Factory Reset does not report default setting. Also powercycle of the sensor does not solve this.
These values are updated correctly to default settings when:
-powercycle the ESP32 or
-the mobile app connects to the sensor.

Hope this testinformation provide some insights.

2025-02-20 04:38 UTC, kbx81 commented on components/sensor/ld2450.rst
> +- **multi_target** (*Optional*): Turn on/off the Multi Target Tracking option. All options from
Hmm, that's not my experience at all, @WiebKastanje. When I factory reset the **LD2450,** the settings revert to the radar's defaults as documented.

Are you factory resetting the **ESP** or the **LD2450**? These are different things.

Factory resetting the ESP does not impact the radar settings, as they are stored on the radar module itself and retrieved from it when the ESP boots. That would explain why you are not seeing the settings revert to their defaults.

When you factory reset the radar module--whether via Bluetooth using the app or using the method provided in the ESPHome component--the settings will not be reflected in ESPHome/HA until the ESP is rebooted, as it only queries the module at startup and settings are not sent from the module to the ESP immediately following a factory reset. This is expected behavior and there's not a way to change this -- it's just how the LD2450 radar module works.

2025-02-20 09:11 UTC, kbx81 approved these changes

2025-02-20 09:16 UTC, merged