Document the modbus server feature
OttoWinter/esphomedocs pull request #3332
Opened 2023-11-05 10:37 UTC by JeroenVanOort

## Description:

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/708

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#4874

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-02-24 12:17 UTC, nagyrobi submitted a review, later dismissed
I fixed the conflicts, but still, there's a contradiction:

`modbus_controller.rst`

_To choose the role, set the role attribute of the Modbus Component upon which this modbus_controller component relies. **client** is the default._

`modbus.rst`

_role (Optional, string): The role of this component, client or server. Defaults to **server**._

I'll let the author to clear this...

2024-05-22 04:00 UTC, jesserockz requested changes

2024-05-22 04:00 UTC, jesserockz commented on components/modbus.rst
> +- **role** (*Optional*, string): The role of this component, ``client`` or ``server``. Defaults to ``server``.
```suggestion
- **role** (*Optional*, string): The role of this component, ``client`` or ``server``. Defaults to ``client``.
```

2024-05-22 04:00 UTC, jesserockz approved these changes

2024-05-22 04:17 UTC, merged