Update alarm docs to reflect changes in PR 5671
OttoWinter/esphomedocs pull request #3334
Opened 2023-11-05 12:17 UTC by hwstar

## Description:
Update documentation to add on_ready and on_chime callbacks, add sensor_type and zone configuration options, and add get_all_sensors_ready() method.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<5671>

## Checklist:

  - [X ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2023-11-09 07:12 UTC, grahambrown11 requested changes

2023-11-09 07:12 UTC, grahambrown11 commented on components/alarm_control_panel/template.rst
> +  - **sensor_type** (*Optional*, string): Sets the sensor type. One of ``delayed``, ``instant``, or ``interior_follower``. (``delayed`` is default if not specified)
please describe what all these mean

2023-11-09 23:21 UTC, hwstar commented on components/alarm_control_panel/template.rst
> +  - **sensor_type** (*Optional*, string): Sets the sensor type. One of ``delayed``, ``instant``, or ``interior_follower``. (``delayed`` is default if not specified)
Docs updated to reflect code changes.

2023-11-14 15:32 UTC, hwstar commented
Section on Trigger Modes added to docs.

2023-12-20 05:35 UTC, jesserockz approved these changes, later dismissed

2023-12-20 11:05 UTC, kbx81 requested changes
Couple little nits, otherwise LGTM

2023-12-20 11:05 UTC, kbx81 commented on components/alarm_control_panel/index.rst
> +This trigger is activated when the logical 'and' of all the alarm sensors change state. This is useful for implementing alarm ready LED's.
```suggestion
This trigger is activated when the logical 'and' of all the alarm sensors change state. This is useful for implementing "alarm ready" LEDs.
```

2023-12-20 11:05 UTC, kbx81 commented on components/alarm_control_panel/index.rst
> +***********************
```suggestion
``on_ready`` Trigger
********************
```

2023-12-20 11:05 UTC, kbx81 commented on components/alarm_control_panel/index.rst
> +***********************
```suggestion
``on_chime`` Trigger
********************
```

2023-12-21 00:36 UTC, jesserockz approved these changes

2023-12-21 01:08 UTC, kbx81 approved these changes

2023-12-21 05:10 UTC, merged