Updated Haier integration documentation to support alarm triggers
OttoWinter/esphomedocs pull request #3474
Opened 2023-12-19 21:18 UTC by paveldn

## Description:

Updated documentation to support new features (alarm triggers and AWAY preset)

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#5965

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2023-12-20 04:30 UTC, jesserockz approved these changes, later dismissed

2023-12-20 11:14 UTC, kbx81 requested changes
Couple little nits, otherwise LGTM

2023-12-20 11:14 UTC, kbx81 commented on components/climate/haier.rst
> +There are two versions of the Haier protocol. The older one is using is an application called SmartAir2 and the newer one - an application called hOn. Both protocols are compatible on the transport l
The added "is" isn't necessary. 🤔

2023-12-20 11:14 UTC, kbx81 commented on components/climate/haier.rst
> +There are two versions of the Haier protocol. The older one is using is an application called SmartAir2 and the newer one - an application called hOn. Both protocols are compatible on the transport l
I might reword this as follows:

```suggestion
There are two versions of the Haier protocol: the older version uses an application called SmartAir2 while the newer version uses an application called hOn. Both protocols are compatible on the transport level but utilize different commands to control appliances.
```

2023-12-20 11:14 UTC, kbx81 commented on components/climate/haier.rst
> +Older Haier models controlled by the SmartAir2 application are using the KZW-W002 module. This module can’t be reused, and you need to replace it with an ESP (RPI pico w) module. The USB connector on
```suggestion
Older Haier models controlled by the SmartAir2 application are using the KZW-W002 module. This module can’t be reused, and you need to replace it with an ESP or RPI Pico W module. The USB connector on the board doesn’t support the USB protocol. It is a UART port that just uses a USB connector. To connect the ESP board to your AC you can cut a USB type A cable and connect wires to the climate connector.
```

2023-12-20 11:32 UTC, paveldn commented
@kbx81 Thanks. English is not my native language, sometimes, I make stupid mistakes

2023-12-20 12:26 UTC, kbx81 approved these changes

2023-12-21 00:10 UTC, jesserockz commented
> kbx81 Thanks. English is not my native language, sometimes, I make stupid mistakes

English **is** my native language and I make stupid mistakes :stuck_out_tongue_closed_eyes:

2023-12-21 00:10 UTC, merged