Add docs for Sharp GP2Y1010AU0F PM2.5 sensor
OttoWinter/esphomedocs pull request #3492
Opened 2023-12-23 22:21 UTC by zry98

## Description:

**Related issue (if applicable):** N/A

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#6007

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-01-02 21:03 UTC, optimusprimespace commented on components/sensor/gp2y1010au0f.rst
> +
You can include here the necessary components to have a functioning setup, 150k ohm resistor & 220 µF capacitor.

2024-01-02 21:03 UTC, optimusprimespace commented on components/sensor/gp2y1010au0f.rst
> +To use this sensor, you need to setup a voltage sensor source (:doc:`ADC sensor <adc>`, but for example also :doc:`ADS1115 <ads1115>`) and pass it to the sensor with the ``sensor`` option, in order t
I don't know if the ADS1115 is fast enough to capture the rapid signal the sensor is giving off, i have to recheck it, but last time i checked 860SPS is 860Hz ->1.1628ms which is higher than the 0.28ms sampling time required by the sensor. So from the ESPHome catalog of supported ADConverters only the MCP3204/3208, MCP3004/3008 and ADC128S102.

2024-09-29 22:14 UTC, jesserockz requested changes

2024-09-29 22:14 UTC, jesserockz commented on components/sensor/gp2y1010au0f.rst
> +              send_every: 3
Examples should be simpler and specific to this component only
```suggestion
    sensor:
      - platform: gp2y1010au0f
        name: 'Indoor PM2.5'
        sensor: REPLACEME
        output: REPLACEME
```

2024-09-29 22:14 UTC, jesserockz commented on components/sensor/gp2y1010au0f.rst
> +- **id** (*Optional*, :ref:`config-id`): Manually specify the ID used for code generation.
We no longer include these on individual pages as they are part of the base sensor schema which is linked and users need to learn.
```suggestion
```

2024-09-29 22:14 UTC, jesserockz approved these changes

2024-09-30 01:22 UTC, merged