OTA version documentation
OttoWinter/esphomedocs pull request #3552
Opened 2024-01-17 16:43 UTC by tomaszduda23

## Description:

OTA version documentation which allows user to select between OTA v1 and OTA v2.
OTA v1 is default.

**Related issue (if applicable):** fixes <link to issue>

https://github.com/esphome/issues/issues/3318

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

https://github.com/esphome/esphome/pull/6066

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-01-18 10:37 UTC, kbx81 commented on components/ota.rst
> +   Defaults to ``1``.
```suggestion
-  **version** (*Optional*, int): Version of OTA protocol to use. Version 2 is more stable.
   To downgrate to legacy EPSHome, the device should be updated with OTA version 1 first.
   Defaults to ``1``.
```

2024-01-19 03:24 UTC, jesserockz requested changes

2024-01-19 03:24 UTC, jesserockz commented on components/ota.rst
> +   Defaults to ``1``.
As per https://github.com/esphome/esphome/pull/6066/files#r1458250436
```suggestion
   Defaults to ``2``.
```

2024-01-19 03:32 UTC, jesserockz approved these changes

2024-01-19 04:18 UTC, merged