INA2xx component docs
OttoWinter/esphomedocs pull request #3571
Opened 2024-01-24 22:25 UTC by latonita

## Description:
Documentation for component supporting INA228, INA229, INA238, INA239, INA237 power monitors.

**Related issue (if applicable):** fixes
https://github.com/esphome/feature-requests/issues/2549

**Pull request in [esphome](https://github.com/esphome/esphome) ** esphome/esphome#6138

## Checklist:

  - [X] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [X] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-05-01 22:39 UTC, kbx81 requested changes

2024-05-01 22:39 UTC, kbx81 commented on components/sensor/ina2xx.rst
> +
We do not include prerequisite component configuration in examples.
```suggestion
```

2024-05-01 22:39 UTC, kbx81 commented on components/sensor/ina2xx.rst
> +- All other options for I²C device as descibed in respective documentation.
```suggestion
- All other options from :ref:`Sensor <config-sensor>` and :ref:`I²C device <i2c>`.
```

2024-05-01 22:39 UTC, kbx81 commented on components/sensor/ina2xx.rst
> +
As above
```suggestion
```

2024-05-01 22:39 UTC, kbx81 commented on components/sensor/ina2xx.rst
> +        cs_pin: D3
For pin numbers, we're now using this pattern (to force people to use their own pin(s)).
```suggestion
        cs_pin: GPIOXX
```

2024-05-01 22:39 UTC, kbx81 commented on components/sensor/ina2xx.rst
> +- All other options for SPI device as descibed in respective documentation.
```suggestion
- All other options from :ref:`Sensor <config-sensor>` and :ref:`SPI device <spi>`.
```

2024-05-01 22:39 UTC, kbx81 commented on components/sensor/ina2xx.rst
> +All other options from :ref:`Sensor <config-sensor>`. Shorthand notation can be used for the sensors like this:
```suggestion
is reported  separately on each update_interval. The ``name`` option is required for each sensor configured; 
all other options from :ref:`Sensor <config-sensor>` are also supported. Shorthand notation can be used for the sensors like this:
```

2024-05-16 04:50 UTC, jesserockz approved these changes

2024-05-16 04:50 UTC, merged