LTR390 - Correct sensor name error in example
OttoWinter/esphomedocs pull request #3585
Opened 2024-02-01 08:42 UTC by sjtrny

## Description:

Correct sensor name error in example.

**Related issue (if applicable):** NA

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** NA

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [X] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-02-05 05:57 UTC, nagyrobi approved these changes, later dismissed

2024-02-05 06:48 UTC, sjtrny commented
Hi @nagyrobi I think this PR needs to wait until https://github.com/esphome/esphome/pull/6161 is merged. I started adding more changes after I created this PR and forgot to update the description, so this is my fault. Sorry!

2024-02-21 04:08 UTC, jesserockz requested changes

2024-02-21 04:08 UTC, jesserockz commented on components/sensor/ltr390.rst
> +        resolution: 20
We try not to add config lines that are not required to let the user read the documentation and understand what they are able to change.
```suggestion
```

2024-02-21 04:09 UTC, jesserockz approved these changes

2024-02-21 04:10 UTC, merged