Add documentation for ADS1118
OttoWinter/esphomedocs pull request #3606
Opened 2024-02-16 04:57 UTC by solomondg1

## Description:

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#5711

## Checklist:

  - [1 ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [1 ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-03-08 17:37 UTC, lboue reviewed
Looks good

2024-03-10 21:01 UTC, jesserockz requested changes

2024-03-10 21:01 UTC, jesserockz commented on components/sensor/ads1118.rst
> +sensor platform to create individual sensors that will report the voltage to Home Assistant.
While we love Home Assistant, it's not needed on individual sensor pages. =)
```suggestion
sensor platform to create individual sensors that will report the voltage.
```

2024-03-10 21:01 UTC, jesserockz commented on components/sensor/ads1118.rst
> +adc options:
```suggestion
ADC Options:
^^^^^^^^^^^^
```

2024-03-10 21:01 UTC, jesserockz commented on components/sensor/ads1118.rst
> +temperature options: none
```suggestion
Temperature Options:
^^^^^^^^^^^^^^^^^^^^

None
```

2024-03-10 21:01 UTC, jesserockz commented on components/sensor/ads1118.rst
> +        - lambda: return x * 28.3 / 6.5;
We don't add things like this to sensor docs. It is up to the user to find out what they need exactly from the filter documentation
```suggestion
```

2024-03-10 21:01 UTC, jesserockz commented on components/sensor/ads1118.rst
> +-  **id** (*Optional*, :ref:`config-id`): Manually specify the ID used for code generation.
```suggestion
- **type** (*Optional*): ``adc``(default) or ``temperature``
- **ads1118_id** (*Optional*, :ref:`config-id`): Manually specify the ID of the
   :ref:`ADS1118 Hub <ads1118-component>` you want to use this sensor.
- **update_interval** (*Optional*, :ref:`config-time`): The interval to check the sensor. Defaults to ``60s``.
- All other options from :ref:`Sensor <config-sensor>`.
```

2024-03-10 21:18 UTC, jesserockz approved these changes

2024-03-10 22:09 UTC, merged