add doc for daikin_arc
OttoWinter/esphomedocs pull request #3709
Opened 2024-03-24 16:35 UTC by magicbear

## Description:

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#6425

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-03-25 22:11 UTC, jesserockz commented
As this is a feature matched with a PR in `esphome/esphome`, please target your PR to the `next` branch and rebase.

Thanks
Jesse

2024-03-27 06:13 UTC, magicbear commented
> As this is a feature matched with a PR in `esphome/esphome`, please target your PR to the `next` branch and rebase.
> 
> Thanks Jesse

rebased to next

2024-03-27 07:54 UTC, jesserockz requested changes

2024-03-27 07:54 UTC, jesserockz commented on components/climate/climate_ir.rst
> +- **use_fahrenheit** (*Optional*, boolean): U.S. models of the Daikin BRC remote send the temperature in Fahrenheit, if your remote shows Fahrenheit and can not be changed to Celsius then set this to
This is not in the code..

2024-03-27 18:55 UTC, jesserockz approved these changes

2024-03-27 18:56 UTC, merged