Add opt3001 component
OttoWinter/esphomedocs pull request #3795
Opened 2024-04-24 17:46 UTC by ccutrer

## Description:

Documentation for the opt3001 component

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-06-24 01:44 UTC, ccutrer commented
I'm still waiting on a review for the corresponding PR to core.

2024-08-24 01:55 UTC, ccutrer commented
Still waiting

2024-10-25 02:05 UTC, ccutrer commented
Not stale

2024-12-25 01:57 UTC, ccutrer commented
Not stale

2025-02-24 02:07 UTC, ccutrer commented
Not stale

2025-06-05 18:30 UTC, ccutrer commented
Not stale

2025-06-21 04:19 UTC, kbx81 requested changes

2025-06-21 04:19 UTC, kbx81 commented on components/index.rst
> +    OPT3001, components/sensor/opt3001, opt3001.jpg, Lux
Please insert this alphabetically in the list.

2025-06-23 06:01 UTC, kbx81 approved these changes

2025-06-23 19:31 UTC, merged