Documentation for new OpenTherm component
OttoWinter/esphomedocs pull request #3800
Opened 2024-04-26 07:52 UTC by olegtarasov

## Description:

This PR adds documentation for the new OpenTherm component in ESPHome.

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-09-11 06:25 UTC, kbx81 requested changes
Mostly clean-up & copy fixes.

Also, please wrap all lines at no more than 120 characters.

2024-09-11 06:25 UTC, kbx81 commented on components/opentherm.rst
> +OpenTherm (OT) is a standard communications protocol used in central heating systems for the communication between a central heating appliances and a thermostatic controller.
```suggestion
OpenTherm (OT) is a standard communications protocol used in central heating systems for the communication between central heating appliances and a thermostatic controller.
```

2024-09-11 06:25 UTC, kbx81 commented on components/opentherm.rst
> +    This component acts only as an OpenTherm master (i.e. a thermostat or controller) and not as a slave or gateway. You can no longer use your existing thermostat if you control your boiler through
```suggestion
    This component acts only as an OpenTherm master (for example, a thermostat or controller) and not as a slave or gateway. Your existing thermostat is not usable while you use ESPHome with this component to control your boiler.
```

2024-09-11 06:25 UTC, kbx81 commented on components/opentherm.rst
> +First of all you need to define the OpenTherm hub in your configuration. Note that most OpenTherm adapters label ``in`` and ``out`` pins relative to themselves, and this component labels its ``in`` a
```suggestion
First, you need to define the OpenTherm hub in your configuration. Note that most OpenTherm adapters label ``in`` and ``out`` pins relative to themselves; this component labels its ``in`` and ``out`` pins relative to the microcontroller ESPHome runs on. As such, your bridge's ``in`` pin becomes the hub's ``out`` pin and vice-versa.
```

2024-09-11 06:25 UTC, kbx81 commented on components/opentherm.rst
> +By default this component adheres to ESPHome recommendations and doesn't block the loop while communicating with the boiler. Unfortunately, some other components (like Dallas temperature sensors) don
```suggestion
The use of some components (like Dallas temperature sensors) may result in lost frames and protocol warnings from OpenTherm. Since OpenTherm is resilient by design and transmits its messages in a constant loop, these dropped frames don't usually cause any problems. Still, if you want to decrease the number of protocol warnings in your logs, you can enable ``sync_mode`` which will block ESPHome's main application loop until a single conversation with the boiler is complete. This can greatly reduce the number of dropped frames, but usually won't eliminate them entirely. With ``sync_mode`` enabled, in some cases, ESPHome's main application loop may be blocked for longer than is recommended, resulting in warnings in the logs. If this bothers you, you can adjust ESPHome's log level by adding the following to your configuration:
```

2024-09-11 06:25 UTC, kbx81 commented on components/opentherm.rst
> +      # ...
```suggestion
        heat_output: setpoint
        # ...
```

2024-09-11 06:25 UTC, kbx81 commented on components/opentherm.rst
> +- ``ch2_active``: Central Heating 2 active
The section heading is `switches`, but then the first thing talked about is how to not use the switches. 😅

I think I would reorganize this section like so:

```suggestion

Switches are available to allow manual toggling of any of the following five status codes:

- ``ch_enable``: Central Heating enabled
- ``dhw_enable``: Domestic Hot Water enabled
- ``cooling_enable``: Cooling enabled
- ``otc_active``: Outside temperature compensation active
- ``ch2_active``: Central Heating 2 active

If you do not wish to have switches, the same values can be permanently set in the hub configuration, like so:

.. code-block:: yaml

    opentherm:
      ch_enable: true
      dhw_enable: true

This is useful when you'd never want to toggle it after the initial configuration.

The default values for these configuration variables are listed below.

For enabling of central heating and cooling, the flag is only sent to the boiler if the following conditions are met:

- the flag is set to true in the hub configuration,
- the switch is on i(f configured),
- the setpoint or cooling control value is not 0 (if configured)

For domestic hot water and outside temperature compensation, only the first two conditions are necessary.

The last point ensures that central heating is not enabled if no heating is requested as indicated by a setpoint of 0. If you use a number as the setpoint input and use a minimum value higher than 0, you **must** use the ``ch_enable`` switch to turn off your central heating. In such a case, the flag will be set to true in the hub configuration and the setpoint is always larger than 0, so including a switch is the only way you can turn off central heating. (This also holds for cooling and CH2.)
```

2024-09-11 06:25 UTC, kbx81 commented on components/opentherm.rst
> +
These can be omitted, they're not really relevant to the example.

```suggestion
```

2024-09-11 06:25 UTC, kbx81 commented on components/opentherm.rst
> +
As above
```suggestion
```

2024-09-11 09:04 UTC, kbx81 requested changes
Couple other things I missed earlier -- for pins in documentation, we use `GPIOXX` to prompt the user to specify their own pins.

2024-09-11 09:04 UTC, kbx81 commented on components/opentherm.rst
> +      out_pin: 5
```suggestion
      in_pin: GPIOXX
      out_pin: GPIOXX
```

2024-09-11 09:04 UTC, kbx81 commented on components/opentherm.rst
> +      out_pin: 26
```suggestion
      in_pin: GPIOXX
      out_pin: GPIOXX
```

2024-09-11 09:04 UTC, kbx81 commented on components/opentherm.rst
> +      out_pin: 26
```suggestion
      in_pin: GPIOXX
      out_pin: GPIOXX
```

2024-09-14 06:45 UTC, olegtarasov commented
@kbx81 Thank you for the review! I've applied your suggestions and wrapped most lines at 120 characters.

2024-09-14 07:04 UTC, kbx81 submitted a review, later dismissed

2024-09-14 07:15 UTC, kbx81 submitted a review, later dismissed

2024-09-14 07:18 UTC, kbx81 approved these changes, later dismissed

2024-09-15 04:43 UTC, kbx81 approved these changes, later dismissed

2024-10-10 01:42 UTC, kbx81 submitted a review, later dismissed

2024-10-25 22:52 UTC, FreeBear-nc commented
You describe values such as t_set as inputs - Surely they are outputs.

`diff --git a/components/opentherm.rst b/components/opentherm.rst
index 819120c9..91945ae3 100644
--- a/components/opentherm.rst
+++ b/components/opentherm.rst
@@ -147,7 +147,7 @@ output and number components by default:
 - ``auto_min_value`` (boolean): Automatically configure the minimum value to a value reported by the boiler. Not
   available for all inputs.
 
-The following inputs are available:
+The following outputs are available:
 
 - ``t_set``: Control setpoint: temperature setpoint for the boiler's supply water (°C)
 
`

2024-10-26 06:04 UTC, olegtarasov commented
@FreeBear-nc You are correct, this terminology looks confusing. It's part of the original documentation from Arthur Rump that I didn't change. But I wouldn't call them inputs either because then we can declare an input as an output, and it's confusing :)  I would rewrite this whole section as following:

```
Numerical values
*****************

There are three ways to set a numerical value:

- As an input sensor, defined in the hub configuration:

[skipped] 

  This can be useful if you have an external thermostat-like device that provides the setpoint as a sensor.

- As a number:

[skipped] 

  This is useful if you want full control over your boiler and want to manually set all values.

- As an output:

[ skipped ]

The following numerical values are available:```

2024-11-11 04:30 UTC, jesserockz requested changes

2024-11-11 04:30 UTC, jesserockz commented on components/opentherm.rst
Please add the standard `See Also` block at the bottom of the page with at least a link to the header files and the ghedit link.

2024-11-11 10:16 UTC, kbx81 commented on components/opentherm.rst
Once this is done, this has my 👍🏻

2024-11-11 10:50 UTC, olegtarasov commented on components/opentherm.rst
Done!

2024-11-12 03:19 UTC, jesserockz approved these changes

2024-11-12 03:19 UTC, merged