Add documentation for StatsD component
OttoWinter/esphomedocs pull request #3802
Opened 2024-04-29 07:27 UTC by Links2004

## Description:

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#6642

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-08-28 06:32 UTC, Links2004 commented
Waiting for review and merge, not stale

2024-09-02 23:02 UTC, jesserockz requested changes

2024-09-02 23:02 UTC, jesserockz commented on components/statsd.rst
> +    ESP32 will work fine with or without Arduino as Framework.
Not required as there is no alternatives for users to use =)
```suggestion
```

2024-09-02 23:02 UTC, jesserockz commented on components/statsd.rst
> +      update_interval: 10s
It is preferred that these examples be sparse as they should only show basic/required syntax and not optional fields.

If full examples are desired, they can go at the bottom of the page under the configuration variables.

```suggestion
    statsd:
      host: REPLACEME
      sensors:
        id: some_sensor
        name: test1.sensor

    sensor:
      platform: ...
      id: some_sensor
```

2024-09-02 23:02 UTC, jesserockz commented on components/statsd.rst
> +This example will generate a metric named `esphome.test1.wifi.signal` with the value of the `wifi_signal` sensor.
```suggestion
This example will generate a metric named `test1.sensor` with the value of the `some_sensor` sensor.
```

2024-09-02 23:02 UTC, jesserockz commented on components/statsd.rst
> +- **id** (**Required**, id): The ID of the sensor.
```suggestion
- **id** (**Required**, :ref:`config-id`): The ID of the sensor.
```

2024-09-02 23:02 UTC, jesserockz commented on components/statsd.rst
This page is missing the `see also` section at the bottom with at a minimum: 
```rst
See Also
--------

- :ghedit:`Edit`
```

2024-09-03 10:05 UTC, Links2004 commented on components/statsd.rst
added

2024-09-05 00:57 UTC, jesserockz approved these changes

2024-09-05 00:57 UTC, merged