Apds9306
OttoWinter/esphomedocs pull request #3826
Opened 2024-05-09 04:25 UTC by aodrenah

## Description:
Added instructions for the apds9306 component.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>
I am doing that pr next so if I can edit, i'll put it here.

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-05-23 07:19 UTC, kbx81 commented
I think you may have had a bad rebase -- there are some changes in here that don't belong in this PR. Please fix. 🙂

2024-05-23 07:23 UTC, kbx81 commented on components/sensor/apds9306.rst
> +- **id** (*Optional*, :ref:`config-id`): Set the ID of this sensor for use in lambdas.
```suggestion
```

2024-07-22 05:14 UTC, jesserockz requested changes

2024-07-22 05:14 UTC, jesserockz commented on components/sensor/apds9306.rst
> +- **name** (**Required**, string): The name for the sensor.
`name` is included in the sensor core config so not needed here.

```suggestion
```

2024-07-22 05:14 UTC, jesserockz approved these changes

2024-07-22 05:29 UTC, merged