Document UDP component
OttoWinter/esphomedocs pull request #3918
Opened 2024-06-06 05:13 UTC by clydebarrow

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-06-06 06:18 UTC, nagyrobi commented
[This cookbook entry](https://esphome.io/cookbook/http_request_sensor) becomes outdated with this component, i guess it could be removed when this is merged.

2024-06-06 06:22 UTC, clydebarrow commented
Yes. There are many shortcomings with using HTTP for the task - it's heavyweight since it requires the webserver, it's insecure (no encryption) and it requires polling.On 6 June 2024 16:19, "H. Árkosi Róbert" ***@***.***> wrote:
This cookbook entry becomes outdated with this component, i guess it could be removed when this is merged.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-06-06 06:35 UTC, nagyrobi commented
Let's remove it within this PR.

2024-07-24 19:52 UTC, nagyrobi submitted a review, later dismissed

2024-08-30 04:00 UTC, jesserockz requested changes

2024-08-30 04:00 UTC, jesserockz commented on components/udp.rst
> +- **binary_sensors** (*Optional*, list): A list of binary sensor IDs to be broadcast.
```suggestion
- **binary_sensors** (*Optional*, list): A list of binary sensor IDs to be broadcast.

  - **id** (**Required**, :ref:`config-id`): The id of the binary sensor to be used
  - **broadcast_id** (*Optional*, string): The id to be used for this binary sensor in the broadcast. Defaults to the same as the internal id.

```

2024-08-30 04:00 UTC, jesserockz commented on components/udp.rst
> +  - **broadcast_id** (*Optional*, :ref:`config-id`): The id to be used for this sensor in the broadcast. Defaults to the same as the internal id.
```suggestion
  - **broadcast_id** (*Optional*, string): The id to be used for this sensor in the broadcast. Defaults to the same as the internal id.
```

2024-08-30 04:00 UTC, jesserockz commented on components/udp.rst
> +the component will broadcast that sensor's state, but since this may not be d by a consumer, the UDP component
Not sure what the `d` is supposed to be here?
```suggestion
the component will broadcast that sensor's state, but since this may not be delivered to a consumer, the UDP component
```

2024-08-30 04:00 UTC, jesserockz commented on components/udp.rst
> +delivery, but in practice unless the network has failed, updates will eventually be d, albeit possibly after
Another `d`? Delivered?
```suggestion
delivery, but in practice unless the network has failed, updates will eventually be delivered, albeit possibly after
```

2024-08-30 08:59 UTC, jesserockz approved these changes

2024-08-30 09:00 UTC, merged