Bump HeatpumpIR - add protocols
OttoWinter/esphomedocs pull request #3996
Opened 2024-06-26 12:49 UTC by nagyrobi

Adding protocols
```
airway
bgh_aud
panasonic_altdke
vaillantvai8
r51m
```
possible from HeatpumpIR to 1.0.27

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#6996

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-07-11 20:28 UTC, jesserockz requested changes

2024-07-11 20:28 UTC, jesserockz commented on components/climate/climate_ir.rst
> +      pin: GPIO32
Examples are not to have real pin numbers.
```suggestion
      pin: GPIOXX
```

2024-07-11 20:28 UTC, jesserockz commented on components/climate/climate_ir.rst
> +      - platform: coolix
Lets remove this so it forces the users to change it correctly
```suggestion
      - platform: REPLACEME
```

2024-07-11 20:28 UTC, jesserockz commented on components/climate/climate_ir.rst
> +        number: GPIO14
```suggestion
        number: GPIOXX
```

2024-07-11 20:58 UTC, jesserockz commented on components/climate/climate_ir.rst
> +| Midea                                 | ``midea_ir``        | yes                  |
No need to remove the link to the lower section...
```suggestion
| :ref:`Midea<midea_ir>`                | ``midea_ir``        | yes                  |
```

2024-07-11 21:07 UTC, jesserockz requested changes

2024-07-11 21:07 UTC, jesserockz commented on components/climate/climate_ir.rst
> +.. note::
```suggestion
``daikin_arc`` Climate
-------------------------
```

2024-07-11 21:07 UTC, jesserockz commented on components/climate/climate_ir.rst
> +.. note::
We should leave the heading there so they populate correctly in the sidebar. Really I think these sections should stay in the same order as the table at the top please.

```suggestion
``zhlt01`` Climate
---------------------
```

2024-07-11 21:07 UTC, jesserockz commented on components/climate/climate_ir.rst
> +    The ``zhlt01`` climate and protocol, based on the ZH/LT-01 remote controller, is used with many locally branded airconditioners, like: Eurom, Chigo, Tristar, Tecnomaster, Elgin, Geant, Tekno, Top
```suggestion
The ``zhlt01`` climate and protocol, based on the ZH/LT-01 remote controller, is used with many locally branded airconditioners, like: Eurom, Chigo, Tristar, Tecnomaster, Elgin, Geant, Tekno, Topair, Proma, Sumikura, JBS, Turbo Air, Nakatomy, Celestial Air, Ager, Blueway, Airlux, etc.
```

2024-07-11 21:07 UTC, jesserockz commented on components/climate/climate_ir.rst
> +    The Daikin ARC remotes (``daikin_arc`` climate, ``daikin_arc417``, ``daikin_arc480`` protocols) are used by the japanese model of Daikin.
```suggestion
The Daikin ARC remotes (``daikin_arc`` climate, ``daikin_arc417``, ``daikin_arc480`` protocols) are used by the japanese model of Daikin.
```

2024-07-12 08:14 UTC, nagyrobi commented
@jesserockz the concept was to declutter the page by removing the empty sections of the entries which don't have any specific configuration, and move the notes to a common block at the end of the file.

2024-07-12 08:42 UTC, nagyrobi commented
Here's a new approach.

2024-07-12 08:55 UTC, jesserockz commented on components/climate/climate_ir.rst
> +The assumed state is being restored at boot (if you set ``esp8266_restore_from_flash: true``).
`esp8266_restore_from_flash` is deprecated and will be removed in a future version. The correct option is `restore_from_flash` under the `esp8266` component.

2024-07-12 09:03 UTC, jesserockz commented
> No reason to show something in the sidebar which doesn't have any specific configuration option, just a generic note.

Fair enough. Happy for it to not be in the sidebar. And its good now, the previous versions without "headers" would scroll down and because the notes were all just bunched at the bottom, you wouldnt actually know where it was scrolling to.

2024-07-12 13:28 UTC, nagyrobi commented
> `esp8266_restore_from_flash` is deprecated and will be removed in a future version. The correct option is `restore_from_flash` under the `esp8266` component.

Corrected. Also please check out https://github.com/esphome/esphome-docs/pull/4040, https://github.com/esphome/esphome-docs/pull/4041, https://github.com/esphome/esphome-docs/pull/4042, https://github.com/esphome/esphome-docs/pull/4043.

2024-07-12 21:19 UTC, jesserockz approved these changes

2024-07-12 21:19 UTC, merged