Add documentation for the new espnow component
OttoWinter/esphomedocs pull request #4086
Opened 2024-07-26 16:39 UTC by nielsnl68

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#7141

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-07-27 08:40 UTC, nielsnl68 commented
@esphomebot generate image esp_now

2025-01-27 10:46 UTC, RoboMagus requested changes

2025-01-27 10:46 UTC, RoboMagus commented on components/espnow.rst
> +- **auto_add_peer** (*Optional*, boolean): Enable adding new peers automatically.
Duplicate `auto_add_peer`

2025-08-01 04:50 UTC, jesserockz approved these changes

2025-08-01 04:51 UTC, merged