Add NAU7802 docs
OttoWinter/esphomedocs pull request #4092
Opened 2024-07-29 05:48 UTC by cujomalainey

## Description:
Add docs for NAU7802

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#6291

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-09-27 01:41 UTC, jesserockz requested changes
Don't forget to add this sensor to the `/index.rst` file in the appropriate section.

2024-09-27 01:41 UTC, jesserockz commented on components/sensor/nau7802.rst
> +- **name** (**Required**, string): The name for the ADC.
We don't add `name` or `id` in entity docs
```suggestion
```

2024-09-27 01:41 UTC, jesserockz commented on components/sensor/nau7802.rst
> +- **id** (*Optional*, :ref:`config-id`): Manually specify the ID used for code generation.
```suggestion
```

2024-10-07 03:08 UTC, jesserockz approved these changes

2024-10-07 03:10 UTC, merged

2024-10-07 03:47 UTC, cujomalainey commented
Thanks for doing the last part, busy week