Initial NPI-19 pressure sensor documentation
OttoWinter/esphomedocs pull request #4105
Opened 2024-08-03 00:18 UTC by bakerkj

## Description:

**Related issue (if applicable): none

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#7181

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-08-05 14:35 UTC, nagyrobi commented
As this is a feature matched with a PR in `esphome/esphome`, please target your PR to the `next` branch and rebase.

Thanks

2024-08-05 21:05 UTC, bakerkj commented
> As this is a feature matched with a PR in `esphome/esphome`, please target your PR to the `next` branch and rebase.

Sorry. I missed that. Now it is targeted against next.

Thanks!

2024-10-03 03:07 UTC, jesserockz requested changes

2024-10-03 03:07 UTC, jesserockz commented on components/sensor/npi19.rst
> +the value ``1638`` maps to approximately ``10%`` of the maximum value of the sesnor (e.g. ``0.5`` psi for a ``5`` psi sensor);
```suggestion
the value ``1638`` maps to approximately ``10%`` of the maximum value of the sensor (e.g. ``0.5`` psi for a ``5`` psi sensor);
```

2024-10-03 03:07 UTC, jesserockz commented on components/sensor/npi19.rst
> +            - 14746 -> 4.5
Dont need extra info in the example. If people read the page properly they will see the linear calibration suggested below. If you want, you can include the `copy` sensor in the calibration section

```suggestion
    # Example configuration entry
    sensor:
      - platform: npi19
        raw_pressure:
          name: "Raw Pressure"
        temperature:
          name: Temperature
```

2024-10-07 02:59 UTC, jesserockz approved these changes

2024-10-07 02:59 UTC, merged