LVGL cookbook
OttoWinter/esphomedocs pull request #4110
Opened 2024-08-05 13:33 UTC by nagyrobi

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-08-06 11:56 UTC, nagyrobi commented
Due to too many conflicts, the doc has been resumbmitted as a new PR: https://github.com/esphome/esphome-docs/pull/4115

2024-08-12 07:44 UTC, kbx81 requested changes
Fix a couple links

2024-08-12 07:44 UTC, kbx81 commented on cookbook/lvgl.rst
> +Here are a couple recipes for various interesting things you can do with :ref:`lvgl-main` in ESPHome.
```suggestion
Here are a couple recipes for various interesting things you can do with :doc:`/components/lvgl/index` in ESPHome.
```

2024-08-12 07:44 UTC, kbx81 commented on cookbook/lvgl.rst
> +- :ref:`lvgl-main`
```suggestion
- :doc:`/components/lvgl/index`
```

2024-09-15 09:46 UTC, jesserockz submitted a review, later dismissed

2024-09-15 09:59 UTC, jesserockz approved these changes

2024-09-15 10:00 UTC, merged