HLW8032 documentation
OttoWinter/esphomedocs pull request #4124
Opened 2024-08-11 09:37 UTC by rici4kubicek

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#7241

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2025-11-04 02:15 UTC, swoboda1337 requested changes
Docs need to be updated to md format. Thanks!

2025-11-07 17:48 UTC, swoboda1337 requested changes

2025-11-07 17:48 UTC, swoboda1337 commented on content/components/sensor/hlw8032.md
> +  Defaults value `1.72`  .
Extra spaces before .

2025-11-07 17:48 UTC, swoboda1337 commented on content/components/sensor/hlw8032.md
> +  rx_pin: RX
```suggestion
  rx_pin: GPIOXX
```

2025-11-07 17:48 UTC, swoboda1337 commented on content/components/sensor/hlw8032.md
> +Additionally, you need to set the baud rate to `4800`   and the `EVEN`   parity.  The device sends multiple updates per second, so you
Lines should be less than 120 cols long

2025-11-07 17:48 UTC, swoboda1337 commented on content/components/sensor/hlw8032.md
> +  Defaults value `1.72`  .
'Defaults value' should be changed to 'Default value'

2025-11-07 17:48 UTC, swoboda1337 commented on content/components/sensor/hlw8032.md
> +
Blank line

2025-11-10 19:19 UTC, swoboda1337 requested changes

2025-11-10 19:19 UTC, swoboda1337 commented on content/components/sensor/hlw8032.md
> +The `hlw8032`   sensor platform allows you to use your HLW8032 voltage/current and power sensors
```suggestion
The `hlw8032` sensor platform allows you to use your HLW8032 voltage/current and power sensors
```

2025-11-10 19:44 UTC, swoboda1337 requested changes

2025-11-10 19:44 UTC, swoboda1337 commented on content/components/sensor/hlw8032.md
> +- [sensor-filters](#sensor-filters)
```suggestion
- [Sensor Filters](#sensor-filters)
```

2025-11-10 19:44 UTC, swoboda1337 commented on content/components/sensor/hlw8032.md
> +  All options from [Sensor](#config-sensor).
```suggestion
  All options from [Sensor](#config-sensor).
- **uart_id** (*Optional*, [ID](#config-id)): Manually specify the ID of the [UART Component](#uart) if you want
  to use multiple UART buses.
```

2025-11-10 19:44 UTC, swoboda1337 commented on content/components/sensor/hlw8032.md
> +to have an [UART bus](#uart) in your configuration with the `rx_pin` connected to the HLW8032.
```suggestion
As the communication with the HLW8032 is done using UART, you need
to have a [UART bus](#uart) in your configuration with the `rx_pin` connected to the HLW8032.
```

2025-11-10 19:44 UTC, swoboda1337 commented on content/components/sensor/hlw8032.md
> +([datasheet](https://v4.cecdn.yun300.cn/100001_2107285051/DS_HLW8032_EN_Rev1.5.pdf)) sensors with
```suggestion
The `hlw8032` sensor platform allows you to use your HLW8032 voltage/current and power sensors
([datasheet](https://v4.cecdn.yun300.cn/100001_2107285051/DS_HLW8032_EN_Rev1.5.pdf)) with
```

2025-11-14 20:31 UTC, swoboda1337 requested changes

2025-11-14 20:31 UTC, swoboda1337 commented on content/components/sensor/hlw8032.md
> +ESPHome. This sensor is commonly found in M5Stack modules.
```suggestion
The `hlw8032` sensor platform allows you to use your HLW8032 voltage/current and power sensors
([datasheet](https://v4.cecdn.yun300.cn/100001_2107285051/DS_HLW8032_EN_Rev1.5.pdf)) with
ESPHome. This sensor is commonly found in M5Stack modules.
```

2025-11-14 20:31 UTC, swoboda1337 commented on content/components/sensor/hlw8032.md
> +to have an [UART bus](#uart) in your configuration with the `rx_pin` connected to the HLW8032.
```suggestion
As the communication with the HLW8032 is done using UART, you need
to have a [UART bus](#uart) in your configuration with the `rx_pin` connected to the HLW8032.
```

2025-11-14 20:31 UTC, swoboda1337 commented on content/components/sensor/hlw8032.md
> +- [sensor-filters](#sensor-filters)
```suggestion
- [Sensor Filters](#sensor-filters)
```

2025-11-14 20:32 UTC, swoboda1337 commented
You resolved all my requested changes without fixing them. I would commit the changes but for some reason github is not letting me.

2025-11-14 20:34 UTC, swoboda1337 approved these changes

2025-12-06 20:08 UTC, swoboda1337 requested changes

2025-12-06 20:08 UTC, swoboda1337 commented on content/components/sensor/hlw8032.md
> +to have a [UART bus](#uart) in your configuration with the `rx_pin` connected to the HLW8032.
Hi, sorry I forgot about this PR and would like to merge in the next few days. Can you merge the latest or allow me to make changes? There were some updates and this will fail lint.

2025-12-06 20:14 UTC, swoboda1337 commented
Please click allow maintainers to modify. Thanks!

2025-12-06 20:16 UTC, rici4kubicek commented
> Please click allow maintainers to modify. Thanks!

Done.

2025-12-06 20:30 UTC, swoboda1337 commented
Thanks, I will also get claude to add a second about the PF pin, pulse_counter can use that to calculate kwh etc.

2025-12-07 09:07 UTC, rici4kubicek commented
> Thanks, I will also get claude to add a second about the PF pin, pulse_counter can use that to calculate kwh etc.

I have updated branch with the latest changes.

@swoboda1337 Regarding the PF pin, yes you are right, there is also possibility to use this feature with this chip. I do not have this implemented yet. If you agree, I'll add this feature in the next PR.

2025-12-07 14:06 UTC, swoboda1337 commented
> > Thanks, I will also get claude to add a second about the PF pin, pulse_counter can use that to calculate kwh etc.
> 
> I have updated branch with the latest changes.
> 
> @swoboda1337 Regarding the PF pin, yes you are right, there is also possibility to use this feature with this chip. I do not have this implemented yet. If you agree, I'll add this feature in the next PR.

I don't think you have to implement anything though. I think this will work: https://esphome.io/components/sensor/pulse_counter/

I think putting an example here is good enough?

2025-12-07 14:08 UTC, swoboda1337 commented
This example seems like it would work for this chip: https://esphome.io/components/sensor/pulse_counter/#counting-total-pulses

2025-12-07 20:11 UTC, swoboda1337 commented
I added some examples, please take a look, see if they make sense. I also added a new picture that had a transparent background. 

If all looks good I will merge. Thanks

2025-12-07 20:11 UTC, swoboda1337 submitted a review, later dismissed

2025-12-07 20:14 UTC, swoboda1337 submitted a review, later dismissed

2025-12-07 20:20 UTC, swoboda1337 commented
Let me know in the next two days so I can merge before beta. Thanks!

2025-12-08 09:01 UTC, rici4kubicek commented
@swoboda1337 Thanks for adding the examples! The implementation looks functional at first glance.
However, based on the documentation (which I find incomplete), this chip requires a slightly different approach for the PF pin. It needs dynamic recalculation of the coefficient to convert pulses to kWh. Unfortunately, the datasheet doesn't provide clear guidance on this, and existing implementations I've found online vary significantly in their approach.

Given this uncertainty, I'd prefer not to include the PF pin and energy calculation in this PR for now. We can revisit this feature in a future PR once I've had more time to thoroughly investigate the correct implementation method.
Would it be okay to proceed with the current PR without the PF pin handling examples?

2025-12-08 13:56 UTC, swoboda1337 commented
Let me remove most of the detail then, can still mention the PF pin then without an example. Can add the the example once you have time to test it.

2025-12-08 14:03 UTC, swoboda1337 commented
How does that look?

2025-12-08 14:05 UTC, rici4kubicek commented
It looks fine now.

2025-12-08 14:06 UTC, swoboda1337 approved these changes

2025-12-08 14:06 UTC, swoboda1337 commented
Thanks!

2025-12-08 14:06 UTC, merged