I2s comm fmt
OttoWinter/esphomedocs pull request #4250
Opened 2024-09-15 21:47 UTC by PxPert

## Description:

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#7449

## Checklist:

  - [X] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-09-15 22:34 UTC, jesserockz requested changes
Please rebase or recreate your branch from `next`

2024-09-16 07:14 UTC, PxPert commented
Hi! Sorry, my mistake when forking the esphome-docs repo. I've now rebased and it should now be able to be merged with the next brach :)

2024-09-19 04:14 UTC, jesserockz commented on components/speaker/i2s_audio.rst
> +  - ``stand_i2s``
```suggestion
  - ``stand_i2s`` (Default)
```

2024-09-19 04:14 UTC, jesserockz approved these changes

2024-09-19 04:16 UTC, merged