OpenThread Component
OttoWinter/esphomedocs pull request #4306
Opened 2024-10-05 17:11 UTC by lboue

## Description:
OpenThread Component

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2025-05-30 14:41 UTC, lboue commented
I've made the adjustments to the new tree structure.

2025-06-11 05:27 UTC, jesserockz requested changes

2025-06-11 05:27 UTC, jesserockz commented on components/index.rst
> +    OpenThread, components/openthread, openthread.png
This should go under Network Hardware instead of here.

2025-06-11 05:27 UTC, jesserockz commented on components/openthread.rst
> +Thread uses the same RF technology as Zigbee (IEEE 802.15.4) but provides IP connectivity similar to Wi-Fi. Unlike Zigbee, Thread by itself does not allow controlling devices: It is just a communicat
```suggestion
Thread uses the same RF technology as Zigbee (IEEE 802.15.4) but provides IP connectivity similar to Wi-Fi. Unlike Zigbee, Thread by itself does not allow controlling devices: It is just a communication protocol. To control the Thread devices, a higher-level protocol is required: Matter or Apple HomeKit or :doc:`ESPHome API </components/api>` .
```

2025-06-11 05:27 UTC, jesserockz commented on components/openthread.rst
> +        platform_version: 6.8.1
TMI
```suggestion
      framework:
        type: esp-idf
```

2025-06-11 08:41 UTC, lboue commented on components/index.rst
> +    OpenThread, components/openthread, openthread.png
Fixed

2025-06-11 08:44 UTC, lboue commented
The requested changes have been implemented.

2025-06-11 10:01 UTC, jesserockz approved these changes

2025-06-11 10:01 UTC, merged