Allow vars in remote packages
OttoWinter/esphomedocs pull request #4342
Opened 2024-10-15 07:13 UTC by pszafer

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-10-16 03:18 UTC, jesserockz commented on components/packages.rst
> +- **files** (**Required**, list of strings or list of { name, vars }): List of files to include.
```suggestion
- **files** (**Required**, list of strings or list of ``{ name, vars }``): List of files to include.
```

2024-12-16 05:27 UTC, pszafer commented
hi fyi, @jesserockz this PR and Esphome PR are ready for review

2025-02-26 00:57 UTC, jesserockz approved these changes, later dismissed

2025-02-26 00:59 UTC, jesserockz requested changes

2025-02-26 00:59 UTC, jesserockz commented on components/packages.rst
> +          - name: file1.yml
```suggestion
          - path: file1.yml
```

2025-02-26 00:59 UTC, jesserockz commented on components/packages.rst
> +          - name: file1.yml #Same file can be specified multiple times with different vars.
```suggestion
          - path: file1.yml #Same file can be specified multiple times with different vars.
```

2025-02-26 00:59 UTC, jesserockz commented on components/packages.rst
> +- **files** (**Required**, list of strings or list of ``{ name, vars }``): List of files to include.
```suggestion
- **files** (**Required**): List of files to include. Can be one of:
  
  - list of file paths
  - list of objects containing ``path`` and ``vars``

```

2025-02-26 01:02 UTC, jesserockz submitted a review, later dismissed

2025-02-26 01:03 UTC, jesserockz approved these changes

2025-02-26 01:04 UTC, merged