Update i2c.rst
OttoWinter/esphomedocs pull request #4356
Opened 2024-10-20 16:43 UTC by gabest11

## Description:

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-10-20 20:15 UTC, jesserockz requested changes

2024-10-20 20:15 UTC, jesserockz commented on components/i2c.rst
Each component in ESPHome should have it's own documentation page with a matching name.

2024-10-20 22:58 UTC, gabest11 commented
I can only point at spi_device again in my defense, it's also not listed on its own page.

2024-10-22 04:00 UTC, jesserockz commented
> I can only point at spi_device again in my defense, it's also not listed on its own page.

Will add to the list to fix. Thanks

2024-10-22 04:03 UTC, jesserockz approved these changes

2024-10-23 03:23 UTC, merged