Add publish Action for Nextion components
OttoWinter/esphomedocs pull request #4368
Opened 2024-10-22 09:40 UTC by pkejval

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#7646

## Checklist:

  - [X] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2024-10-24 23:15 UTC, kbx81 commented on components/binary_sensor/nextion.rst
> +------------------------------------------
```suggestion
----------------------------------------
```

2024-10-24 23:18 UTC, kbx81 requested changes
Just a couple RST tweaks -- also, please wrap long lines at no more than 120 columns. Thanks!

2024-10-24 23:18 UTC, kbx81 commented on components/binary_sensor/nextion.rst
> +------------------------------------------
```suggestion
----------------------------------------
```

2024-10-24 23:18 UTC, kbx81 commented on components/binary_sensor/nextion.rst
> +Configuration options:
```suggestion
Configuration variables:
```

2024-10-24 23:18 UTC, kbx81 commented on components/sensor/nextion.rst
> +---------------------------------------
```suggestion
``sensor.nextion.publish`` Action
---------------------------------
```

2024-10-24 23:18 UTC, kbx81 commented on components/switch/nextion.rst
> +---------------------------------------
```suggestion
``switch.nextion.publish`` Action
---------------------------------
```

2024-10-24 23:19 UTC, kbx81 requested changes
...aaannnddd realized I missed these, too. haha

2024-10-24 23:19 UTC, kbx81 commented on components/sensor/nextion.rst
> +Configuration options:
```suggestion
Configuration variables:
```

2024-10-24 23:19 UTC, kbx81 commented on components/text_sensor/nextion.rst
> +Configuration options:
```suggestion
Configuration variables:
```

2024-10-25 05:13 UTC, pkejval commented
> Just a couple RST tweaks -- also, please wrap long lines at no more than 120 columns. Thanks!

Why do I need to wrap lines? Original documentation has lines longer than 120 columns. These should be wrapped too? I think this is beyond my PR.

2024-10-26 00:11 UTC, kbx81 commented
> > Just a couple RST tweaks -- also, please wrap long lines at no more than 120 columns. Thanks!
> 
> Why do I need to wrap lines? Original documentation has lines longer than 120 columns. These should be wrapped too? I think this is beyond my PR.

[Last bullet point here](https://esphome.io/guides/contributing#notes) -- please do this on any new lines you've added to the document. You don't need to through the whole document and do this, but we also certainly wouldn't mind if you do. 😄

2024-10-30 04:26 UTC, kbx81 approved these changes

2024-11-23 04:52 UTC, merged