Guides for noobs (ESPHome on Docker Desktop & Adding Devices)
OttoWinter/esphomedocs pull request #4411
Opened 2024-11-04 16:59 UTC by trip5

## Description: Two guides added
- Beginner’s Guide to Installing ESPHome on Docker Desktop
- Beginner’s Guide to Adding Devices

They are step-by-step guides with waaay too many pictures that should help people get their feet wet in ESPHome.

I think there are more than a few people out there who would love to get into ESPHome but the documentation is a bit dense.

**Related issue (if applicable):** None.

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** N/A

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [X] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [X] Link added in `/index.rst` when creating new documents for new components or cookbook.
      Actually, I changed the link to "Getting Started with the ESPHome Command Line" to the new "Beginner’s Guide to Adding Devices" which contains links to the various methods of getting ESPHome running (just in case).

2024-11-04 17:41 UTC, trip5 commented on guides/beginners_guide_adding_devices.rst
> +
Fixed.

2024-11-04 17:42 UTC, trip5 commented on guides/beginners_guide_docker_desktop.rst
> +``Pull`` the image, then ``Run`` with these options:
Not sure any of these are applicable.

2024-11-04 17:44 UTC, trip5 commented on guides/beginners_guide_docker_desktop.rst
> +
Not applicable, I'm sure.  It's alluded to that you can download specific versions if need be already.  Docker Desktop does not need memory-limiting.  Windows already does that for you.

2024-11-09 07:23 UTC, trip5 commented
The nitpick suggestions were pretty good.  I'll put them in.

2024-11-11 18:09 UTC, trip5 commented
I think I have to tag someone.  @jesserockz I know it's not your usual - but I think these guides would be very helpful for noobs.

2024-12-27 09:33 UTC, jekader commented
Thank you @trip5 for this contribution, indeed it's a bit hard for beginners to grasp what steps are needed to set up esphome for the first time.

2025-02-16 04:09 UTC, DjordjeMandic commented
Thanks 👍! I will try following this guide to make sure nothing has changed. Gotta test it if it's really noob-proof 😁

2025-02-16 05:08 UTC, kbx81 commented on guides/beginners_guide_adding_devices.rst
> +        version: "${project_version}"
This syntax is outdated and won't be supported after this (February) release. See https://github.com/esphome/esphome/pull/8118

I would also not use the 8266 in examples. Use a more modern chip such as an ESP32 or supported variant.

2025-02-16 05:15 UTC, kbx81 reviewed
I started looking through this but am far from done -- so this review is nowhere near complete. I figured we should talk about it more (on Discord) before I spend too much time. 😇

Please wrap lines longer than 120 characters at 120 characters.

2025-02-16 05:15 UTC, kbx81 commented on guides/beginners_guide_adding_devices.rst
> +The first thing you should do is edit your ``Secrets`` file. This contains reusable elements that you can "hide" from the main ESPHome GUI.
> This guide is for people who are not so tech-orientated but wish to get their feet wet with ESPHome.

What are "secrets"? Why do I need them? What is an example of something that should be considered a "secret"?

2025-02-16 05:15 UTC, kbx81 commented on guides/beginners_guide_adding_devices.rst
> +Also, it allows you to copy and paste YAMLs from your own code to share with others (and vice versa) without the worry of leaking details about your home network.
Maybe swap this with the line above -- provide context, _then_ talk about editing the secrets file.

2025-02-16 13:43 UTC, ximex commented on guides/beginners_guide_adding_devices.rst
> +    for example, "MyWifi" for 2.4Ghz and "MyWifi5G" for 5Ghz.
is this really recommended to name the SSID's different? then it wouldn't be possible to "roam" between 2.4GHz and 5GHz easily

2025-02-16 13:43 UTC, ximex commented on guides/beginners_guide_adding_devices.rst
> +            **Redo**  : ``Ctrl + Shift + Y``
maybe put the `Shift` into `(Shift)`. Often (not always) `Shift` isn't needed on linux

2025-02-16 16:20 UTC, trip5 commented on guides/beginners_guide_adding_devices.rst
> +    for example, "MyWifi" for 2.4Ghz and "MyWifi5G" for 5Ghz.
Well, it might be.  But it's a divided issue and if sorting out issues, this is often recommended.  But, point noted and I'll add a bit more here.

  https://www.reddit.com/r/HomeNetworking/comments/197o4f7/is_it_still_better_to_have_different_ssids_for/

2025-02-16 16:30 UTC, trip5 commented
> I started looking through this but am far from done -- so this review is nowhere near complete. I figured we should talk about it more (on Discord) before I spend too much time. 😇

Sure.  Sorry, I don't know Discord too well but I'm often online anyways these days.  In the ESPHome Discord as Trip5 but my ID is _trip5_.

2025-02-16 16:31 UTC, trip5 commented on guides/beginners_guide_adding_devices.rst
> +The first thing you should do is edit your ``Secrets`` file. This contains reusable elements that you can "hide" from the main ESPHome GUI.
Good point.

2025-02-16 16:49 UTC, trip5 commented on guides/beginners_guide_adding_devices.rst
> +            **Redo**  : ``Ctrl + Shift + Y``
Well, if that's the case, I can just rename the tabs.

2025-02-16 16:52 UTC, trip5 commented on guides/beginners_guide_adding_devices.rst
> +        version: "${project_version}"
Oh, indeed.  I knew that too as I personally use the "new" way in all my YAMLs.  Switching to ESP32 is probably a good idea as well.

I'll see if I can link to the "boards" list in here as well.

2025-02-16 17:33 UTC, trip5 commented on guides/beginners_guide_adding_devices.rst
> +Also, it allows you to copy and paste YAMLs from your own code to share with others (and vice versa) without the worry of leaking details about your home network.
Considered carefully and edited... included a bit more about WHY to use a secrets file.

2025-02-16 17:41 UTC, trip5 commented
A lot of minor edits, too.  I think I had stuck to 140-150 character lines so I went through it and restructured so all but
`.. figure:: :alt:`s stop before the 120th column.

2025-02-17 08:30 UTC, kbx81 commented on guides/beginners_guide_adding_devices.rst
> +    for example, "MyWifi" for 2.4Ghz and "MyWifi5G" for 5Ghz.
We should not recommend one way or the other.

I'll spare you the details but (personally and as a former network/Wi-Fi admin) I absolutely _despise_ when people split their Wi-Fi networks into separate SSIDs for 2.4, 5 and now 6 GHz -- I avoid doing so at all costs/it's a last resort. As far as ESPs are concerned, they lack the hardware to even "see" 5 or 6 GHz so there is really no reason to worry about them roaming/attempting to roam onto these frequencies, anyway. I've been using a single SSID for all frequencies here (2.4, 5 and 6 GHz) for years with nearly 60 ESPs and I've got no connectivity issues with any of them at all.

That said, I've got no issues with creating a separate "IoT" SSID/VLAN (there are good reasons to do this) -- it's arguably a good practice. 🙂

2025-02-17 08:35 UTC, kbx81 commented on guides/beginners_guide_adding_devices.rst
> +    for example, "MyWifi" for 2.4Ghz and "MyWifi5G" for 5Ghz.
> I put all of my bands on the same SSID and let the clients decide. I’ve created an additional single-band SSID for difficult clients that refuse to connect or frequently drop connections.

I think this is the best advice. If you need a "compatibility" SSID for poorly-behaving clients, just do that -- I have that here, as well. But don't break apart all of your SSIDs for all clients just because a couple of them are misbehaving.

2025-02-17 08:48 UTC, trip5 commented on guides/beginners_guide_adding_devices.rst
> +    for example, "MyWifi" for 2.4Ghz and "MyWifi5G" for 5Ghz.
How about this:

Although you should have no issues using the same SSID name for 2.4Ghz and 5Ghz, if you encounter any issues with a device maintaining its connection, you may want to consider using a different SSID name or guest network on the 2.4Ghz band for your IOT devices.

2025-02-17 09:07 UTC, kbx81 commented on guides/beginners_guide_adding_devices.rst
> +sources (such as Github) much easier as well.
Don't use words like "things", "stuff" and even "ones". It's not specifically bad but it's a bit too...informal. Sentences also should not start with "so".

```suggestion
The ``secrets.yaml`` file is where you'll store information that you don't want to accidentally share or otherwise
hard-code into your device's YAML configuration file(s). It's also useful because it provides a single place in which
to store common values; this way, if you need to change one of them, you won't need to update every individual device's
file, which can save you a lot of time when you have many devices!

When you keep these secret values in a separate file, you can confidently copy and paste YAML from your files and share
it with others. You don't need to worry about accidentally sharing the details of your home network, such as your Wi-Fi
SSID name and password.
```

2025-02-17 09:21 UTC, kbx81 commented on guides/beginners_guide_adding_devices.rst
> +    or guest network on the 2.4Ghz band for your IOT devices.
Let's be very careful with our words here so as to not create any confusion. Theoretically possible, yes, but..."not many"? Other than the C5--which is brand-new and I'm not even sure is readily available yet--which ESPs support frequencies other than 2.4 GHz? 😇

```suggestion
    Supported Espressif microcontrollers only support the 2.4 Ghz frequency range for Wi-Fi.

    If you're experiencing connectivity issues, see our :ref:`FAQ <wifi-problems>`.
```

2025-02-17 09:28 UTC, ximex commented on guides/beginners_guide_adding_devices.rst
> +    for example, "MyWifi" for 2.4Ghz and "MyWifi5G" for 5Ghz.
> if you encounter any issues with a device maintaining its connection, you may want to consider using a different SSID name or guest network on the 2.4Ghz band for your IOT devices **(, that have connection problems)**.

2025-02-17 12:21 UTC, ximex commented on guides/beginners_guide_adding_devices.rst
> +            **Redo**  : ``Ctrl + Shift + Y``
merge Windows and Linux or what do you mean?

2025-02-17 17:53 UTC, trip5 commented on guides/beginners_guide_adding_devices.rst
> +            **Redo**  : ``Ctrl + Shift + Y``
I mean I made "Windows" into "Windows / Linux" and made that tab "Other Linux."  Linux users should be knowledgeable enough to which one is theirs.

2025-02-17 17:55 UTC, trip5 commented on guides/beginners_guide_adding_devices.rst
> +    for example, "MyWifi" for 2.4Ghz and "MyWifi5G" for 5Ghz.
Not sure where the other compare went.  But I accepted your suggesting as "Short & concise and link for issues.  Good."

Linking to another place for help clears it up a lot.

2025-02-17 17:57 UTC, trip5 commented on guides/beginners_guide_adding_devices.rst
> +sources (such as Github) much easier as well.
I like your changes.  You're right about informal language.

2025-02-17 18:00 UTC, trip5 commented
@kbx81 Thanks a lot for helping out with this.  Actually, I had a few users of my Clock firmware (which can use but doesn't require Home Assistant) ask numerous questions how to install, and I wanted to help ease the journey a bit.

Do you actually have the ability to put this in ESPHome Docs?  Is it alright that the main page will link to the "Beginner’s Guide to Adding Devices"?

2025-02-17 22:13 UTC, kbx81 commented
> @kbx81 Thanks a lot for helping out with this. Actually, I had a few users of my Clock firmware (which can use but doesn't require Home Assistant) ask numerous questions how to install, and I wanted to help ease the journey a bit.

Happy to help -- thanks for putting in the effort! 🍻

> Do you actually have the ability to put this in ESPHome Docs? Is it alright that the main page will link to the "Beginner’s Guide to Adding Devices"?

We do need a friendly, detailed "beginner's guide" -- I think we have a bit of a gap there. Would we link to it from the main page? ...probably? We've been discussing various changes to our documentation, but nothing specific has come to mind yet and it's mostly just been kicking around ideas.

2025-02-17 22:29 UTC, trip5 commented
Well, lol, I mean I already edited the main page as so:
![image](https://github.com/user-attachments/assets/d9af88c7-60c1-4f3c-8ef9-b8ef32ad4c76)
(screenshot from the deploy preview here: https://deploy-preview-4411--esphome.netlify.app/ )

I'm no dummy at command line but putting it on the front page when can be off-putting for new users... I tried (and failed) and I think only ESPHome OGs and hardcore users will go for it.  But it might be useful (for everyone) to have both linked on the front?

I just rechecked https://esphome.io/guides/getting_started_command_line and it's a little better than it was when I started this doc but... I think I glazed over when I saw "Go open that file in an editor of your choice."  Maybe this one should be renamed to something to indicate it's for advanced users?

2025-02-17 22:38 UTC, kbx81 commented
> I'm no dummy at command line but putting "command line" on the front page as a "getting started" guide can be off-putting for new users... I tried (and failed) and I think only ESPHome OGs and hardcore users will go for it. But it might be useful (for everyone) to have both linked on the front?

All of the tooling is command-line based so it's pretty unavoidable once you get a bit deeper into ESPHome (beyond the EDB alone, that is).

> I just rechecked [esphome.io/guides/getting_started_command_line](https://esphome.io/guides/getting_started_command_line) and it's a little better than it was when I started this doc but... I think I glazed over when I saw "Go open that file in an editor of your choice." Maybe this one should be renamed to something to indicate it's for advanced users?

I recently re-worked the "from HA" guide and it's on my list to re-work the CLI guide, as well -- as I think you're suggesting, it could also use some work. haha

2025-02-18 07:29 UTC, trip5 commented
EDB?  Is that the WebUI for ESPHome?  To be fair, I've managed quite well without resorting to command line (and from what I read, the Docker install doesn't even have it).  Also, to be fair, Windows is "good enough" for most people and they think `cmd` is some sort of super-hacker trickery.  Using a GUI like ESPHome is actually enjoyable (unlike ArduinoUI).

What reasons would there be to use the command line in ESPHome? -- I mean except esptool.

BTW, I'm very willing to help out on the CLI guide if you'd like.  I don't mind experimenting with it again!

2025-02-19 00:00 UTC, kbx81 commented
> EDB?

"ESPHome Device Builder" -- my informal name for the tool & saves a lot of typing. haha

> I've managed quite well without resorting to command line (and from what I read, the Docker install doesn't even have it). Also, to be fair, Windows is "good enough" for most people and they think `cmd` is some sort of super-hacker trickery. Using a GUI like ESPHome is actually enjoyable (unlike ArduinoUI).

Admittedly I'm sort of looking at this through the lens of a developer, so the EDB isn't really useful for me; I think if you have any desire at all to do development/poking around under the hood, the EDB starts to break down as it isn't particularly accommodating for that. It's a friendly front-end for editing YAML and getting it installed onto a device, but not so much a "real" development tool.

> What reasons would there be to use the command line in ESPHome? -- I mean except esptool.

Literally all of the build tooling runs in a terminal. If you're doing anything more "advanced" than just editing YAML, compiling it and installing it onto a device, you end up in a terminal. haha

A situation we see a lot of is people running the EDB as an add-on to an HA instance they've already set up on some SBC (Raspberry Pi, O-Droid or now even HA Yellow/Green). Compiling takes _an eternity_ on most SBCs but we find a lot of people don't realize that there is "another way" and that you can run the ESPHome tooling locally and then compiling a config takes well under a minute as opposed to over an hour.

Personal preference comes into the picture, too. I _by far_ prefer to use VSCode as opposed to some other text editor running in my web browser -- it's not uncommon that I have many device configurations open simultaneously (in tabs) and am copy/pasting stuff between them. Doing that in the EDB is cumbersome at best. Keep in mind that I have nearly 60 ESPHome devices running here so I have _a lot_ of configs...and that's not to mention all of the development work I do on a day-to-day basis.

2025-02-19 06:46 UTC, trip5 commented
> Literally all of the build tooling runs in a terminal. If you're doing anything more "advanced" than just editing YAML, compiling it and installing it onto a device, you end up in a terminal. haha
OK. This is true. Even compiling is a terminal.  Usually non-interactive but terminal still.

> on most SBCs but we find a lot of people don't realize that there is "another way" and that you can run the ESPHome tooling locally and then compiling a config takes well under a minute as opposed to over an hour.
Can confirm.  Moved from a Pi 4 to an ODroid x86 for this exact reason.  Never considered the compiler could be run locally.

> many device configurations open simultaneously (in tabs) and am copy/pasting stuff between them. Doing that in the EDB is cumbersome at best.
Also true.  I usually end up resorting to Notepad++ and VSStudio as well... and several tabs open as well. But for new users... they should figure out their own personal preference.  And I think new users will (like me) start with 2 or 3 ESPHome devices.  Some may never move past that.  I myself still prefer Tasmota for switches and lights.  The thought of having 20 more YAMLs - all of them almost the same - annoys me.  But there's a tool in development `esphome-editor` that is geared towards multiple devices with similar configurations.  I'll get around to it eventually.  Right now in a temporary living situation so most of my smart devices are just gathering dust until the move is complete and I can get back to "living ten minutes in the future" (as I tell my wife).

2025-04-25 04:15 UTC, trip5 commented
Not stale.

2025-05-25 18:38 UTC, trip5 commented
Making another effort to get this some proper attention.  I've resolved the conflict with `index.rst` and re-added a link to my Beginner's Guide to the main page.  I really do think it would be helpful to give new users a step-by-step walk-through but with a bit more detail than what is in the `hassio` guide... and certainly a bit easier to step up to the WebUI than the command line or wading through guides.

2025-05-28 09:52 UTC, jesserockz requested changes
I don't like having a guide on Docker Desktop specifically. It will be something that goes out of date if Docker Desktop decides to change something. We provide a page for docker directly with the image names which should be enough for people to use with whatever cli/gui they decide to use, and they should follow the set-up guides for those tools directly.

2025-05-28 17:51 UTC, trip5 commented
> It will be something that goes out of date if Docker Desktop decides to change something.

You're not wrong.  Removed those files and the link to it completely.

2025-06-11 20:46 UTC, trip5 commented on guides/beginners_guide_adding_devices.rst
> +
All suggestions taken.

2025-06-11 20:46 UTC, trip5 commented on guides/beginners_guide_adding_devices.rst
> +Your first use-case will surely be different but the principles will be the same.
All suggestions taken.

2025-06-11 20:57 UTC, trip5 commented on guides/beginners_guide_adding_devices.rst
> +But in most cases, when dealing with ESP8266, it is ``esp8255`` or sometimes ``esp12e`` (which has only 1M of flash memory).
Fixing now.

2025-06-11 20:57 UTC, trip5 commented on guides/beginners_guide_adding_devices.rst
> +      Both are acceptable but curly brackets are used to avoid errors so it's best to use curly brackets.
Fixing now.

2025-06-11 21:18 UTC, trip5 commented
Sorry that took so long.  Slipped my mind to make more changes....  A lot of little changes made on the suggestion of the AI.  Many were important.

2026-01-31 20:35 UTC, ximex commented
i would wait with this PR until https://github.com/esphome/dashboard/pull/756 is merged. than this PR needs some updates

2026-01-31 21:05 UTC, trip5 commented
> i would wait with this PR until [esphome/dashboard#756](https://github.com/esphome/dashboard/pull/756) is merged. than this PR needs some updates

I kept up with this PR for a year... then life happened and I moved countries.  Is there actual interest in this PR?  If yes, I will absolutely update it to match the upcoming UI changes... when it happens.  Ping me if I'm not working on it soon enough (I don't always keep my ESPHome container up-to-date).

2026-06-30 04:45 UTC, closed without merging