Ntc simulation
OttoWinter/esphomedocs pull request #4485
Opened 2024-11-30 14:57 UTC by rhabacker

Ref https://github.com/esphome/esphome/pull/xxx

## Description:
This pr adds documentation for the `ntcsim` sensor platform.

**Related issue (if applicable):**

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here> - will be added after esphome PR has been created

## Checklist:

  - [x] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2025-02-20 08:20 UTC, rhabacker commented
Anything left to do for this pull request ?

2025-02-20 14:54 UTC, DjordjeMandic requested changes

2025-02-20 14:54 UTC, DjordjeMandic commented on components/sensor/ntcsim.rst
> +- **calibration** (**Required**, float): The calibration parameters of the sensor - see above
```suggestion
- **calibration** (**Required**, float or list): The calibration parameters of the sensor - see above
```

2025-02-20 21:02 UTC, DjordjeMandic submitted a review, later dismissed

2025-03-06 22:32 UTC, clydebarrow commented
What was the reason for using an include rather than putting the new filters inline? The issue with that is it results in creation of two new pages as well as the text appearing in the sensor page. It may well be that the sensor folder could do with a reorganisation but that's outside the scope of this PR.

2025-03-07 16:02 UTC, rhabacker commented
> What was the reason for using an include rather than putting the new filters inline? 

Including everything in one file makes it difficult to get a sorted view and add new entries in the right place. Keeping parts of the documentation separate and including them in other files is already used in other places. 

> The issue with that is it results in creation of two new pages as well as the text appearing in the sensor page.

Fixed with commit 727c653

> It may well be that the sensor folder could do with a reorganisation but that's outside the scope of this PR.

This is intended with https://github.com/esphome/esphome-docs/pull/4735

2025-03-08 02:39 UTC, clydebarrow commented
It's best not to force-push unless needed to recover from a hopeless mess. The commits will be squashed when merging anyway, and force-pushing obscures what changes have been made, which makes reviewing harder.

2025-03-08 02:41 UTC, clydebarrow commented
> This is intended with #4735

So defer that reorganisation until then, others may have opinions about it. Just keep it inline for now to keep the PRs separate.

2025-03-08 08:38 UTC, rhabacker commented
> > This is intended with #4735
> 
> So defer that reorganisation until then, others may have opinions about it. Just keep it inline for now to keep the PRs separate.

Where should new filter documents be inserted? At the end after `lambda` or after `throttle_average` to at least partially maintain an alphabetical order?

2025-03-08 08:52 UTC, clydebarrow commented
Your guess is as good as mine, and probably not so important since it will be revised in due course anyway.

2025-05-01 05:37 UTC, clydebarrow approved these changes

2025-05-01 05:37 UTC, merged