Mac local installation update
OttoWinter/esphomedocs pull request #4516
Opened 2024-12-19 17:08 UTC by swifty99

## Description:

I have tried a lot of different install procedures. This has been flawless since.

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [x] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2025-01-23 12:57 UTC, shvmm commented on guides/installing_esphome.rst
> +    Version: 2024.12.0  # Version number may vary
Version number may vary comment can be moved to its own sentence

2025-01-25 09:47 UTC, swifty99 commented on guides/installing_esphome.rst
> +    Version: 2024.12.0  # Version number may vary
ok

2025-01-27 17:23 UTC, clydebarrow requested changes

2025-01-27 17:23 UTC, clydebarrow commented on guides/installing_esphome.rst
> +ESPHome supports macOS and will run without issues.
This is a bold promise. Perhaps just say that ESPHome supports macOS, and there are several ways to install it.

2025-01-27 17:23 UTC, clydebarrow commented on guides/installing_esphome.rst
> +An easy way for installation is via `Homebrew <https://brew.sh/>`_:
I'd suggest listing here the installation techniques - brew, pip and cloning the repo. Then document each method subsequently with a heading for each one.

2025-01-27 17:23 UTC, clydebarrow commented on guides/installing_esphome.rst
> +Install Python from the official site. Then, install ESPHome with
Expand this somewhat and make the code block level not inline, so make it stand out better. The Linux example below is an example to follow. Add a "Pip installation" sub-heading to make it easy to identify.

2025-01-28 21:01 UTC, swifty99 commented on guides/installing_esphome.rst
> +ESPHome supports macOS and will run without issues.
ok, true.

2025-01-30 00:05 UTC, clydebarrow approved these changes

2025-01-30 00:05 UTC, merged