Add documentation for climate_ir_samsung
OttoWinter/esphomedocs pull request #4533
Opened 2024-12-24 02:23 UTC by jorofi

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#8004

## Checklist:

  - [ X] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [ ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2025-01-27 00:30 UTC, DjordjeMandic requested changes
Could benefit from one short paragraph about confirmed working unit model and remote control model which was used for analysing remote protocol.

2025-01-27 00:30 UTC, DjordjeMandic commented on components/climate/climate_ir.rst
> +
Add more info (which ac model is confirmed to work and model of remote control).

2025-02-11 12:33 UTC, jorofi commented on components/climate/climate_ir.rst
> +
I have added the models that should work with this implementation.

2025-02-11 12:51 UTC, DjordjeMandic submitted a review, later dismissed

2025-10-23 23:38 UTC, swoboda1337 requested changes
Docs need to be converted to md

2026-01-30 01:32 UTC, jorofi commented
Hi @swoboda1337, I’ve addressed all requested changes. Could you please take another look and approve the PR when you have time?

2026-05-10 04:31 UTC, closed without merging