Update rf_bridge.rst
OttoWinter/esphomedocs pull request #4541
Opened 2024-12-28 03:59 UTC by zd3sf

Added references to mightymos firmware

## Description:
1)  Clarified introduction for easier readability.
2) Clarified uart_id configuration variable 
3) Added reference to "Mightymos" firmware alongside Portisch
4) Moved bridge.beep out of portisch section because no Portisch is needed for beeping
5) Add a link for another, more user friendly B1 converter
6) extended the example at the end. 

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] I am merging into `next` because this is new documentation that has a matching pull-request in [esphome](https://github.com/esphome/esphome) as linked above.  
    or
  - [x ] I am merging into `current` because this is a fix, change and/or adjustment in the current documentation and is not for a new component or feature.

  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2025-01-05 07:01 UTC, nagyrobi reviewed
Removed `uart_id` and put `id` twice in the example?

2025-01-05 18:51 UTC, zd3sf commented
Yes UART_id is not a valid syntax in esphome, there's a `id` for the UART component and and id for the bridge component. UART_id was confusing to some users and I have seen few questions about it in the community forum. we can remove the `id` for UART hub as users can go to the UART component page if they want to learn more about UART.

2025-01-05 18:55 UTC, nagyrobi commented
You can't have in the documentation, in the same section two `id` options meaning different things...

2025-01-05 19:49 UTC, zd3sf commented
Now worries, UART id configuration variable was removed.

2025-01-12 05:21 UTC, zd3sf commented
@nagyrobi Is it good to go now?

2025-02-11 05:10 UTC, zd3sf commented
Are we still reviewing this?

2025-03-20 18:46 UTC, zd3sf commented
@nagyrobi. Please let me know if you propose any additional changes.

2025-05-23 02:38 UTC, zd3sf commented
Still pending review?

2025-05-28 05:32 UTC, jesserockz requested changes

2025-05-28 05:32 UTC, jesserockz commented on components/rf_bridge.rst
```suggestion
```

2025-05-28 05:32 UTC, jesserockz commented on components/rf_bridge.rst
> -- **uart_id** (*Optional*, :ref:`config-id`): Manually specify the ID of the UART hub.
This shouldnt be removed

2025-05-28 05:32 UTC, jesserockz commented on components/rf_bridge.rst
> +- **id** (*Optional*, :ref:`config-id`): Manually specify the ID of the RF bridge. Used for code generation and event tracking in home assistant.
Not sure where this statement came from? The id doesn't leave the device
```suggestion
- **id** (*Optional*, :ref:`config-id`): Manually specify the ID of the RF bridge. Used for code generation. 
```

2025-05-29 20:48 UTC, zd3sf commented on components/rf_bridge.rst
> -- **uart_id** (*Optional*, :ref:`config-id`): Manually specify the ID of the UART hub.
Previous reviewer wanted it removed, and I agree. It pertains to UART component, it is shown here as an example of essential config to make the bridge work, but its a configuration variable for UART not RFbridges. Lety me know what you think.

2025-05-29 20:54 UTC, zd3sf commented on components/rf_bridge.rst
> +- **id** (*Optional*, :ref:`config-id`): Manually specify the ID of the RF bridge. Used for code generation and event tracking in home assistant.
hmm I'll phrase it in a better way. The ID of the hub gets attached to events in home assistant. So when the user wants to listen to an RF code, they subscribe to an event based on the ID of the hub.

2025-05-29 21:12 UTC, zd3sf commented on components/rf_bridge.rst
The RF bridge will not run without a UART component. I think it is necessary to keep it in the example config.

2025-05-29 23:09 UTC, jesserockz commented on components/rf_bridge.rst
While this is true, this is not how we write the basic examples in esphome. 
A full example should be added to https://devices.esphome.io/devices/Sonoff-RF-Bridge

2025-05-29 23:11 UTC, jesserockz commented on components/rf_bridge.rst
> -- **uart_id** (*Optional*, :ref:`config-id`): Manually specify the ID of the UART hub.
The `uart_id` is a configuration item of the `rf_bridge` component. 

UART components themselves have `id` which matches the value.

It is automatically filled by ESPHome if there is a single UART entry configured which is why it is optional.

2025-05-29 23:13 UTC, jesserockz commented on components/rf_bridge.rst
> +- **id** (*Optional*, :ref:`config-id`): Manually specify the ID of the RF bridge. Used for code generation and event tracking in home assistant.
As above this id never leaves the device, even for the events in the examples below. 

If you want a specific hub id in the event, you would add one as the user, but that has nothing to do with this is, even if the value is the same

2025-06-05 22:16 UTC, zd3sf commented on components/rf_bridge.rst
> -- **uart_id** (*Optional*, :ref:`config-id`): Manually specify the ID of the UART hub.
You are correct. I will add it back!

2025-06-05 22:31 UTC, zd3sf commented on components/rf_bridge.rst
Yep makes sense. I removed it!

2025-06-05 22:32 UTC, zd3sf commented on components/rf_bridge.rst
> +- **id** (*Optional*, :ref:`config-id`): Manually specify the ID of the RF bridge. Used for code generation and event tracking in home assistant.
Correct again. I removed "Used for code generation."

2025-06-25 23:49 UTC, jesserockz approved these changes

2025-06-25 23:50 UTC, merged