Update gpio.rst
OttoWinter/esphomedocs pull request #581
Opened 2020-05-07 20:21 UTC by 3ative

Added "Example 2 (Use "on_turn_on" instead of template) configuration entry" to "Momentary Switch" section

## Description:
By using **on_turn_on** for a _Momentary Switch_, there's no need for a **template** in the switch section/code.
- I have added a 2nd example.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2020-05-26 23:18 UTC, glmnet commented
A bit hacky... is the `- switch.turn_on` really needed?

2020-05-26 23:19 UTC, glmnet commented
yet another way to do it, the way I do it LOL

````yaml

switch:
  - platform: output
    name: "Porton boton"
    id: porton_boton
    output: gpio_relay_1
    on_turn_on:
      then:
        - delay: 1s
        - switch.turn_off: porton_boton
````

2021-05-09 21:09 UTC, frenck commented
@glmnet I like that suggestion as it is the closest to the source that handles it.

Should we update this PR? Or do you want to open an alternative PR?

I'm happy to jump in as well?

2021-05-09 22:28 UTC, 3ative commented
@frenck 
How is @glmnet 's suggestion any different from my original? 
- Why don't you like mine ?

2021-05-09 22:34 UTC, frenck commented
@3ative I didn't state I didn't like yours.

I stated I think the suggestion from @glmnet is a general better one:

>  I like that suggestion as it is the closest to the source that handles it.

Hence I shared that here.

2021-05-09 22:39 UTC, 3ative commented
@frenck 
Both solutions are valid. Except mine follows the existing example structure, as laid out in the docs and eliminates the need for a 'list' and a 'template' 
My OP was to add an additional 'Example' and not re-write / replace.

2021-05-09 22:42 UTC, frenck commented
> Both solutions are valid

I didn't state that yours wasn't valid either. Please stop guessing/assuming things.

I just stated I think that the example provided by @glmnet, from general code maintenance and the perspective on where one should put responsibilities and how one should separate concerns: his example, in general, is a good one.

2021-05-09 22:46 UTC, 3ative commented
@frenck 
I wasn't suggesting, guessing or assuming your intent, I was merely stating I liked @glmnet example.
Just that it doesn't follow existing Doc example(s) - and therefore is an different approach. Which should therefore be an additional 'example' for another Docs section.

2021-05-09 22:49 UTC, frenck commented
Yes, so lets do that... (and now we are back at my original response in this PR 🤷 )

2021-05-09 22:53 UTC, 3ative commented
@frenck 
Ok, cool let's indeed have both, mine as stated: _"Example 2 (Use "on_turn_on" instead of template) configuration entry"_ in the _"To create momentary switches,..."_ header and @glmnet 's maybe in a more suitable section of the docs.

2021-05-09 23:05 UTC, frenck requested changes

2021-05-09 23:05 UTC, frenck commented on components/switch/gpio.rst
> +          - switch.turn_on: relay
This is the `on_turn_on`... you want to turn it on again?

2021-05-09 23:09 UTC, 3ative commented
> Should we update this PR? ...

I wasn't aware that a PR could be changed or 'updated' - if that is indeed the case then, I'm happy with that. 👍
I see what you mean. Indeed the '- switch.turn_on: relay' is not needed. 

Thanks, when I posted this PR I didn't know as much as I do now.

2021-05-14 17:22 UTC, frenck commented
@3ative Could you remove that unneeded line?

You haven't opened up the PR for maintainers to contribute to, so can't help you out on this one.

2021-05-15 00:34 UTC, 3ative commented
@frenck 
I'm unable to find the option to edit and remove the unwanted line... A little help? 
- How do I make the new changes... or open for maintainers. Cheers.

2021-05-17 08:01 UTC, frenck commented
Oh, I see, you've removed the upstream fork. This means this PR can't go anywhere at this point anymore and can only be solved by opening a new PR.

Closing this PR on this end for now.

../Frenck

2021-05-17 08:01 UTC, closed without merging

2021-05-17 18:59 UTC, 3ative commented
@frenck 
Thanks for the support and helping me understand how use PR correctly.