st7735 Docs
OttoWinter/esphomedocs pull request #608
Opened 2020-05-18 17:37 UTC by SenexCrenshaw

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#1066

## Checklist:

  - [X] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [X] Link added in `/index.rst` when creating new documents for new components or cookbook.

2020-05-26 11:50 UTC, rradar approved these changes

2020-05-28 22:19 UTC, glmnet commented
Check titles there is the word 'expander' a few times

2020-11-20 10:51 UTC, jesserockz requested changes
I notice `OLED` a lot in the docs, but the screen is an LCD...

2020-11-20 10:51 UTC, jesserockz commented on components/display/st7735.rst
> +===================
```suggestion
ST7735 Display
==============
```

2021-01-04 18:45 UTC, jesserockz commented on components/display/st7735.rst
> +There are numerous board types out there. Some initialize differntly as well. This driver will take a few options to narrow down the right settings.
```suggestion
There are numerous board types out there. Some initialize differently as well. This driver will take a few options to narrow down the right settings.
```

2021-01-04 18:46 UTC, jesserockz approved these changes

2021-01-04 18:51 UTC, merged