Adding documentation for Inkbird IBS-TH1 Mini sensor
OttoWinter/esphomedocs pull request #657
Opened 2020-06-24 03:57 UTC by fkirill

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [x] Link added in `/index.rst` when creating new documents for new components or cookbook.

2020-10-04 15:04 UTC, OttoWinter commented on index.rst
> +    Inkbird IBS-TH1 Mini, components/sensor/inkbird_ibsth1_mini, inkbird_isbth1_mini.png
This picture needs to be minified further (148kb is a lot for the main page). I'll update it in a second

2021-01-10 20:15 UTC, jesserockz requested changes

2021-01-10 20:15 UTC, jesserockz commented on guides/faq.rst
> +- In Hass.io: Add the ESPHome repository `https://github.com/esp  / :ref:`mqtt.connected <mqtt-connected_condition>`home/hassio <https://github.com/esphome/hassio>`
Not sure where this came from?

```suggestion
- In Hass.io: Add the ESPHome repository `https://github.com/esphome/hassio <https://github.com/esphome/hassio>`
```

2021-01-10 20:16 UTC, jesserockz approved these changes

2021-02-06 04:04 UTC, merged