Teleinfo
OttoWinter/esphomedocs pull request #666
Opened 2020-07-01 19:00 UTC by 0hax

## Description:

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [*] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [* ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2020-10-02 11:47 UTC, jesserockz approved these changes
LGTM.

2020-11-08 09:10 UTC, jesserockz commented on components/sensor/teleinfo.rst
> +    :image: mhz19.jpg
This looks like the wrong image used?

2020-11-08 09:12 UTC, jesserockz requested changes
Just 1 minor change plus deleting the images that are not actually used please.

2020-11-08 10:37 UTC, 0hax commented
> Just 1 minor change plus deleting the images that are not actually used please.

I removed the image and updated the branch.
Thanks

2020-11-08 10:42 UTC, jesserockz commented on components/sensor/teleinfo.rst
> +    :image: mhz19.jpg
@0hax maybe you missed this? which of the images should be used for SEO?

2020-11-15 18:05 UTC, jesserockz approved these changes

2020-11-15 18:08 UTC, merged