Add separate current/target Tuya Climate multipliers
OttoWinter/esphomedocs pull request #828
Opened 2020-10-30 21:55 UTC by Yarikx

## Description:
Some Tuya thermostats have different multipliers for current and target temperatures.
So the current approach (having a single `temperature_multiplier`) cannot handle both cases.

This is breaking change, it introduces separate multipliers for both values

**Related issue (if applicable):

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):
https://github.com/esphome/esphome/pull/1345

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2020-11-09 19:43 UTC, jesserockz requested changes
Please leave the existing config option in the docs. Maybe add an exclusion note somewhere?

2020-11-09 19:43 UTC, jesserockz commented on components/climate/tuya.rst
> +- **current_temperature_multiplier** (**Optional**, float): A multiplier to modify the current temperature value - :ref:`see below <temperature-multiplier>`.
```suggestion
- **temperature_multiplier** (**Optional**, float): A multiplier to modify the incoming and outgoing temperature values - :ref:`see below <temperature-multiplier>`.
- **current_temperature_multiplier** (**Optional**, float): A multiplier to modify the current temperature value - :ref:`see below <temperature-multiplier>`.
```

2020-11-10 22:03 UTC, Yarikx commented
Moved new config options under the `temperature_multiplier` item. Explained usage a bit more.

2020-11-10 22:29 UTC, jesserockz commented on components/climate/tuya.rst
> +  If the device has different multipliers for current and target temperatures, **temperature_multiplier** can be replaced with either or both of:
The validator I made makes them inclusive so both are required.

```suggestion
  If the device has different multipliers for current and target temperatures, **temperature_multiplier** can be replaced with both of:
```

2020-11-11 17:30 UTC, jesserockz approved these changes

2020-11-11 17:31 UTC, merged