added ST7920 doc
OttoWinter/esphomedocs pull request #907
Opened 2020-12-30 16:42 UTC by marsjan155

## Description:

Docs for ST7920 LCD Display

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2021-05-09 21:20 UTC, frenck approved these changes
@marsjan155, A wild merge conflict appeared, out of nowhere! 🙈 

Could you please rebase this PR onto the latest `next` branch and resolve the merge conflict?

Thanks already! 👍 

../Frenck

2021-05-09 21:20 UTC, frenck requested changes
Now with the correct review status :)

2021-05-12 10:20 UTC, marsjan155 commented
@frenck
rebased and reverted one unnecessary change, should be fine, thanks

2021-05-13 11:12 UTC, frenck commented on components/display/st7920.rst
> +Connect D5 to the E pin you chose for the :ref:`SPI bus <spi>`, connect D7 to the R/W pin and ``RS`` to some GPIO pins one the ESP.
```suggestion
Connect D5 to the E pin you chose for the :ref:`SPI bus <spi>`, connect D7 to the R/W pin and ``RS`` to some GPIO pins on the ESP.
```

2021-05-13 11:15 UTC, frenck approved these changes
✅ Approved. Can be merged as soon as the parent PR gets merged.

2021-08-26 02:33 UTC, merged