Update pzemac.rst due to wrong PIN reference
OttoWinter/esphomedocs pull request #930
Opened 2021-01-10 21:25 UTC by emeggiolaro

## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** esphome/esphome#<esphome PR number goes here>

## Checklist:

  - [ ] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2021-01-11 16:42 UTC, jesserockz approved these changes
Example pins are just examples. A lot of boards and devices have different pins for different functions. 
All though I do somewhat agree that maybe we should use the `GPIOx` variant everywhere and not the board specific pins `Dx` etc.

@glmnet Thoughts? Should we enforce `GPIOx` instead of `Dx` for docs?

2021-01-11 17:44 UTC, glmnet commented
yes, I'd rather use `GPIOxx` instead of `Dx` however this PR is not replacing just PIN names, it's actually using default RX TX pin on ESP8266 which are not default in given example, in this case I would just remove the `TX:` `RX:` config lines as they are default and we do not put defaults in examples.

Using default uart pins will mean you needing to disable serial logging, so this PR should remove RX and TX and add `baud_rate: 0` to `logger:`

RELATED: We could add comments indicating `# ESP8266` or `# ESP32` pin setup, most lovely would be to have a button to view samples for one device or another like some tutorials sites they show you javascript / typescript etc.

2021-05-12 19:36 UTC, frenck requested changes
Added 2 review suggestions to this PR, as per review comments by @glmnet.

@emeggiolaro, could you take a look? Thanks already! 👍 


../Frenck 🚂

2021-05-12 19:36 UTC, frenck commented on components/sensor/pzemac.rst
> +      tx_pin: GPIO1
```suggestion
```

2021-05-12 19:36 UTC, frenck commented on components/sensor/pzemac.rst
>        baud_rate: 9600
```suggestion
      baud_rate: 9600
      
    logger:
      baud_rate: 0
```

2021-11-21 01:39 UTC, closed without merging