Adding that mpr121_id is a valid option for binary_sensor
OttoWinter/esphomedocs pull request #966
Opened 2021-01-28 03:00 UTC by minideezel

## Description:

I had to figure out how to have multiple MPR121's defined, figured I would document the fix so it would be easier for the next guy. Let me know if I did something wrong, this is my first contribution to the docs.

**Related issue (if applicable):** fixes N/A

**Pull request in [esphome](https://github.com/esphome/esphome) with YAML changes (if applicable):** N/A

## Checklist:

  - [x] Branch: `next` is for changes and new documentation that will go public with the next ESPHome release. Fixes, changes and adjustments for the current release should be created against `current`.
  - [ ] Link added in `/index.rst` when creating new documents for new components or cookbook.

2021-03-08 01:10 UTC, glmnet requested changes
Remove line then good to merge

2021-03-08 01:10 UTC, glmnet commented on components/binary_sensor/mpr121.rst
> +        mpr121_id: mpr121_component
This is ok however we don't clutter the docs first example so better this should not go here 

Btw a new check in esphome will make it fail to compile if you declare two hubs and don't specify the one you want to use. So future people will have a better time than you. 

The definition below is ok

2021-03-09 20:59 UTC, minideezel commented
Updated!

2021-03-09 21:24 UTC, glmnet commented
Thanks

2021-03-09 21:24 UTC, merged